package com.peace.users.model;

// Generated Sep 25, 2015 3:40:55 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pmenu generated by hbm2java
 */
@Entity
@Table(name = "pmenu", catalog = "university")
public class Pmenu implements java.io.Serializable {

	private Integer id;
	private String name;
	private String nameEn;
	private String nameRu;
	private Integer parentId=0;
	private String url;
	private Integer orderid;
	private Integer isactive;
	private String icon;
	private Set<PMenuRel> PMenuRels = new HashSet(0);

	private Pmenu parent;
	private List<Pmenu> childs = new ArrayList<Pmenu>();
	
	public Pmenu() {
	}

	public Pmenu(String name, String nameEn, String nameRu, Integer parentId,
			String url, Integer orderid, Integer isactive, String icon,
			Set<PMenuRel> PMenuRels) {
		this.name = name;
		this.nameEn = nameEn;
		this.nameRu = nameRu;
		this.parentId = parentId;
		this.url = url;
		this.orderid = orderid;
		this.isactive = isactive;
		this.icon = icon;
		this.PMenuRels = PMenuRels;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "nameEn", length = 100)
	public String getNameEn() {
		return this.nameEn;
	}

	public void setNameEn(String nameEn) {
		this.nameEn = nameEn;
	}

	@Column(name = "nameRu", length = 100)
	public String getNameRu() {
		return this.nameRu;
	}

	public void setNameRu(String nameRu) {
		this.nameRu = nameRu;
	}

	@Column(name = "parentID")
	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	@Column(name = "url", length = 100)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "orderid")
	public Integer getOrderid() {
		return this.orderid;
	}

	public void setOrderid(Integer orderid) {
		this.orderid = orderid;
	}

	@Column(name = "isactive")
	public Integer getIsactive() {
		return this.isactive;
	}

	public void setIsactive(Integer isactive) {
		this.isactive = isactive;
	}

	@Column(name = "icon", length = 100)
	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parentID",referencedColumnName="id",nullable = false,insertable=false,updatable=false)	
	public Pmenu getParent() {
		return parent;
	}

	public void setParent(Pmenu parent) {
		this.parent = parent;
	}
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "parent",cascade=CascadeType.ALL,orphanRemoval=true)	
	public List<Pmenu> getChilds() {
		return childs;
	}

	public void setChilds(List<Pmenu> childs) {
		this.childs = childs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pmenu")
	public Set<PMenuRel> getPMenuRels() {
		return this.PMenuRels;
	}

	public void setPMenuRels(Set<PMenuRel> PMenuRels) {
		this.PMenuRels = PMenuRels;
	}

}
