package com.peace.users.model;

// Generated Sep 25, 2015 3:40:55 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.CascadeType;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * PUserRoles generated by hbm2java
 */
@Entity
@Table(name = "p_user_roles", catalog = "university")
public class PUserRoles implements java.io.Serializable {

	private Integer id;
	private String role;
	private String definition;
	//private Set<PUserRoleRel> PUserRoleRels = new HashSet(0);
	//private Set<PMenuRel> PMenuRels = new HashSet(0);

	public PUserRoles() {
	}

	public PUserRoles(String role,String definition,
			Set<PUserRoleRel>  PUserRoleRels, Set<PMenuRel> PMenuRels) {
		this.definition = definition;
		this.role = role;
		//this.PUserRoleRels = PUserRoleRels;
		//this.PMenuRels = PMenuRels;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}


	@Column(name = "definition", length = 100)
	public String getDefinition() {
		return definition;
	}

	public void setDefinition(String definition) {
		this.definition = definition;
	}

	@Column(name = "role", length = 100)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

/*	@OneToMany(fetch = FetchType.LAZY, mappedBy = "PUserRoles")
	public Set<PUserRoleRel> getPUserRoleRels() {
		return this.PUserRoleRels;
	}

	public void setPUserRoleRels(Set<PUserRoleRel>  PUserRoleRels) {
		this.PUserRoleRels = PUserRoleRels;
	}*/

/*	@OneToMany(fetch = FetchType.LAZY, mappedBy = "PUserRoles", cascade=CascadeType.ALL,orphanRemoval=true)
	public Set<PMenuRel> getPMenuRels() {
		return this.PMenuRels;
	}

	public void setPMenuRels(Set<PMenuRel> PMenuRels) {
		this.PMenuRels = PMenuRels;
	}*/

}
