package com.peace.users.model;

// Generated Sep 25, 2015 3:40:55 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PUserAuth generated by hbm2java
 */
@Entity
@Table(name = "roles_auth")
public class PUserAuth implements java.io.Serializable {

	private Integer id;	
	private String role;
	private Role tbstudents;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "roleid")	
	public Role getTbstudents() {
		return tbstudents;
	}

	public void setTbstudents(Role tbstudents) {
		this.tbstudents = tbstudents;
	}
	

	@Column(name = "authname", length = 100)
	public String getRole() {
		return this.role;
	}
	public void setRole(String role) {
		this.role = role;
	}

}
