package com.peace.users.model;

// Generated Sep 25, 2015 3:40:55 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PUserRoleRel generated by hbm2java
 */
@Entity
@Table(name = "user_roles", catalog = "university")
public class PUserRoleRel implements java.io.Serializable {

	private Integer id;
	private Integer roleid;
	private Integer userid;
	//private PUserRoles PUserRoles;
//	private User tbstudents;



	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	
	
	@Column(name = "role_id")
	public Integer getRoleid() {
		return roleid;
	}

	public void setRoleid(Integer roleid) {
		this.roleid = roleid;
	}

	@Column(name = "user_id")
	public Integer getUserid() {
		return userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

/*	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id")
	public PUserRoles getPUserRoles() {
		return this.PUserRoles;
	}

	public void setPUserRoles(PUserRoles PUserRoles) {
		this.PUserRoles = PUserRoles;
	}

	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getTbstudents() {
		return tbstudents;
	}

	public void setTbstudents(User tbstudents) {
		this.tbstudents = tbstudents;
	}*/
	

}
