package com.peace.users.model;

// Generated Sep 25, 2015 3:40:55 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Tbbranches generated by hbm2java
 */
@Entity
@Table(name = "tbbranches", catalog = "university")
public class Tbbranches implements java.io.Serializable {

	private Integer id;
	private Integer schoolId;
	private Tbuniversities tbuniversities;
	private String branchName;
	private String branchAddress;
	private String directorName;
	private Set<Tbdepartment> tbdepartments = new HashSet(0);
	//private Set<User> tbstudentses = new HashSet(0);

	public Tbbranches() {
	}

	public Tbbranches(Tbuniversities tbuniversities) {
		this.tbuniversities = tbuniversities;
	}

	public Tbbranches(Tbuniversities tbuniversities, int schoolId, String branchName,
			String branchAddress, String directorName, Set<Tbdepartment> tbdepartments) {
		this.tbuniversities = tbuniversities;
		this.branchName = branchName;
		this.branchAddress = branchAddress;
		this.directorName = directorName;
		this.tbdepartments = tbdepartments;
		//this.tbstudentses = tbstudentses;
		this.schoolId = schoolId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "School_id", length = 45)
	public Integer getSchoolId() {
		return schoolId;
	}

	public void setSchoolId(Integer schoolId) {
		this.schoolId = schoolId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "School_id",referencedColumnName="id", nullable = false,insertable=false,updatable=false)
	@JsonManagedReference
	public Tbuniversities getTbuniversities() {
		return this.tbuniversities;
	}

	public void setTbuniversities(Tbuniversities tbuniversities) {
		this.tbuniversities = tbuniversities;
	}

	@Column(name = "Branch_name", length = 45)
	public String getBranchName() {
		return this.branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	@Column(name = "Branch_address", length = 200)
	public String getBranchAddress() {
		return this.branchAddress;
	}

	public void setBranchAddress(String branchAddress) {
		this.branchAddress = branchAddress;
	}

	@Column(name = "Director_name", length = 45)
	public String getDirectorName() {
		return this.directorName;
	}

	public void setDirectorName(String directorName) {
		this.directorName = directorName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbbranches")
	@JsonBackReference
	public Set<Tbdepartment> getTbdepartments() {
		return this.tbdepartments;
	}

	public void setTbdepartments(Set<Tbdepartment> tbdepartments) {
		this.tbdepartments = tbdepartments;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbbranches")
	@JsonBackReference
	public Set<User> getTbstudentses() {
		return this.tbstudentses;
	}

	public void setTbstudentses(Set<User> tbstudentses) {
		this.tbstudentses = tbstudentses;
	}*/

	/*@Override
	public String toString(){
		return "[\"valuew\":\""+this.id+"\","+
				"\"textw\":\""+this.branchName+"\"]";
		
	}*/
	
	 @Override
	   public String toString()
	   {
	      return "{value=" + id + ", text=" + branchName + "}";
	   }	 
}
