package com.peace.users.model;

// Generated Sep 25, 2015 3:40:55 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Tbdepartment generated by hbm2java
 */
@Entity
@Table(name = "tbdepartment", catalog = "university")
public class Tbdepartment implements java.io.Serializable {

	private Integer id;
	private Tbbranches tbbranches;
	private Tbuniversities tbuniversities;
	private Integer schoolId=0;
	private Integer branchId=0;
	private String departmentName;
	private String departmentHeadName;
	//private Set<User> tbstudentses = new HashSet(0);

	public Tbdepartment() {
	}

	public Tbdepartment(Tbbranches tbbranches, 
			String departmentName) {
		this.tbbranches = tbbranches;
		this.departmentName = departmentName;
	}

	public Tbdepartment(Tbbranches tbbranches,Tbuniversities tbuniversities, int branchId,
			String departmentName, String departmentHeadName) {
		this.tbbranches = tbbranches;
		this.tbuniversities = tbuniversities;
		this.branchId = branchId;
		this.departmentName = departmentName;
		this.departmentHeadName = departmentHeadName;
		//this.tbstudentses = tbstudentses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Branch_id", nullable = false,insertable=false,updatable=false)
	@JsonManagedReference
	public Tbbranches getTbbranches() {
		return this.tbbranches;
	}

	public void setTbbranches(Tbbranches tbbranches) {
		this.tbbranches = tbbranches;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "School_id", nullable = false,insertable=false,updatable=false)
	@JsonManagedReference
	public Tbuniversities getTbuniversities() {
		return tbuniversities;
	}

	public void setTbuniversities(Tbuniversities tbuniversities) {
		this.tbuniversities = tbuniversities;
	}

	@Column(name = "Branch_id", nullable = false)
	public Integer getBranchId() {
		return this.branchId;
	}

	public void setBranchId(int branchId) {
		this.branchId = branchId;
	}

	
	@Column(name = "School_id", nullable = false)
	public Integer getSchoolId() {
		return schoolId;
	}

	public void setSchoolId(Integer schoolId) {
		this.schoolId = schoolId;
	}

	@Column(name = "Department_name", nullable = false, length = 45)
	public String getDepartmentName() {
		return this.departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	@Column(name = "Department_head_name", length = 45)
	public String getDepartmentHeadName() {
		return this.departmentHeadName;
	}

	public void setDepartmentHeadName(String departmentHeadName) {
		this.departmentHeadName = departmentHeadName;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbdepartment")
	@JsonBackReference
	public Set<User> getTbstudentses() {
		return this.tbstudentses;
	}

	public void setTbstudentses(Set<User> tbstudentses) {
		this.tbstudentses = tbstudentses;
	}*/
	
	
	@Override
	public String toString(){
		return "{\"domain\":\"Tbdepartment\","+
				"\"id\":"+this.id+','+
				"\"schoolId\":\""+this.schoolId+"\","+
				//"\"schoolName\":\""+this.tbuniversities.getUnivesityName()+"\","+
				"\"branchId\":\""+this.branchId+"\","+
				//"\"branchName\":\""+this.tbbranches.getBranchName()+"\","+
				"\"departmentName\":\""+this.departmentName+"\","+
				"\"departmentHeadName\":\""+this.departmentHeadName+"\"}";			
				
		
	}

}
