package com.peace.users.model;

// Generated Sep 25, 2015 3:40:55 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tbstudentbus generated by hbm2java
 */
@Entity
@Table(name = "tbstudentbus", catalog = "university")
public class Tbstudentbus implements java.io.Serializable {

	private Integer id;
	private User tbstudents;
	private String schoolStationname;
	private String schoolStationbusline;
	private String homeStationname;
	private String homeStationbusline;

	public Tbstudentbus() {
	}

	public Tbstudentbus(User tbstudents, String schoolStationname,
			String schoolStationbusline, String homeStationname) {
		this.tbstudents = tbstudents;
		this.schoolStationname = schoolStationname;
		this.schoolStationbusline = schoolStationbusline;
		this.homeStationname = homeStationname;
	}

	public Tbstudentbus(User tbstudents, String schoolStationname,
			String schoolStationbusline, String homeStationname,
			String homeStationbusline) {
		this.tbstudents = tbstudents;
		this.schoolStationname = schoolStationname;
		this.schoolStationbusline = schoolStationbusline;
		this.homeStationname = homeStationname;
		this.homeStationbusline = homeStationbusline;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Student_ID", nullable = false)
	public User getTbstudents() {
		return this.tbstudents;
	}

	public void setTbstudents(User tbstudents) {
		this.tbstudents = tbstudents;
	}

	@Column(name = "School_Stationname", nullable = false, length = 45)
	public String getSchoolStationname() {
		return this.schoolStationname;
	}

	public void setSchoolStationname(String schoolStationname) {
		this.schoolStationname = schoolStationname;
	}

	@Column(name = "School_Stationbusline", nullable = false, length = 100)
	public String getSchoolStationbusline() {
		return this.schoolStationbusline;
	}

	public void setSchoolStationbusline(String schoolStationbusline) {
		this.schoolStationbusline = schoolStationbusline;
	}

	@Column(name = "Home_Stationname", nullable = false, length = 45)
	public String getHomeStationname() {
		return this.homeStationname;
	}

	public void setHomeStationname(String homeStationname) {
		this.homeStationname = homeStationname;
	}

	@Column(name = "home_Stationbusline", length = 100)
	public String getHomeStationbusline() {
		return this.homeStationbusline;
	}

	public void setHomeStationbusline(String homeStationbusline) {
		this.homeStationbusline = homeStationbusline;
	}

}
