package com.peace.users.model;

// Generated Sep 25, 2015 3:40:55 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tbstudentgpa generated by hbm2java
 */
@Entity
@Table(name = "tbstudentgpa", catalog = "university")
public class Tbstudentgpa implements java.io.Serializable {

	private Integer id;
	private User tbstudents;
	private Integer gpaFirstcourse;
	private Integer gpaSecondcourse;
	private Integer gpaThirdcourse;
	private Integer gpaFourthcourse;
	private Integer gapFifthcourse;

	public Tbstudentgpa() {
	}

	public Tbstudentgpa(User tbstudents) {
		this.tbstudents = tbstudents;
	}

	public Tbstudentgpa(User tbstudents, Integer gpaFirstcourse,
			Integer gpaSecondcourse, Integer gpaThirdcourse,
			Integer gpaFourthcourse, Integer gapFifthcourse) {
		this.tbstudents = tbstudents;
		this.gpaFirstcourse = gpaFirstcourse;
		this.gpaSecondcourse = gpaSecondcourse;
		this.gpaThirdcourse = gpaThirdcourse;
		this.gpaFourthcourse = gpaFourthcourse;
		this.gapFifthcourse = gapFifthcourse;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "StudentID", nullable = false)
	public User getTbstudents() {
		return tbstudents;
	}

	public void setTbstudents(User tbstudents) {
		this.tbstudents = tbstudents;
	}

	@Column(name = "GPA_Firstcourse")
	public Integer getGpaFirstcourse() {
		return this.gpaFirstcourse;
	}

	

	public void setGpaFirstcourse(Integer gpaFirstcourse) {
		this.gpaFirstcourse = gpaFirstcourse;
	}

	@Column(name = "GPA_Secondcourse")
	public Integer getGpaSecondcourse() {
		return this.gpaSecondcourse;
	}

	public void setGpaSecondcourse(Integer gpaSecondcourse) {
		this.gpaSecondcourse = gpaSecondcourse;
	}

	@Column(name = "GPA_Thirdcourse")
	public Integer getGpaThirdcourse() {
		return this.gpaThirdcourse;
	}

	public void setGpaThirdcourse(Integer gpaThirdcourse) {
		this.gpaThirdcourse = gpaThirdcourse;
	}

	@Column(name = "GPA_Fourthcourse")
	public Integer getGpaFourthcourse() {
		return this.gpaFourthcourse;
	}

	public void setGpaFourthcourse(Integer gpaFourthcourse) {
		this.gpaFourthcourse = gpaFourthcourse;
	}

	@Column(name = "GAP_Fifthcourse")
	public Integer getGapFifthcourse() {
		return this.gapFifthcourse;
	}

	public void setGapFifthcourse(Integer gapFifthcourse) {
		this.gapFifthcourse = gapFifthcourse;
	}

}
