package com.peace.users.model;

// Generated Sep 25, 2015 3:40:55 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Tbuniversities generated by hbm2java
 */
@Entity
@Table(name = "tbuniversities", catalog = "university")
public class Tbuniversities implements java.io.Serializable {

	private Integer id;
	private String univesityName;
	private String universityAddress;
	private String directorName;
	private String phone;
	private String EMail;
	private String web;
	private List<Tbbranches> tbbrancheses = new ArrayList<Tbbranches>();
	private Set<Tbdepartment> tbdepartments = new HashSet(0);
	private Set<User> tbstudentses = new HashSet(0);

	public Tbuniversities() {
	}

	public Tbuniversities(String univesityName, String universityAddress,
			String directorName, String phone, String EMail, String web) {
		this.univesityName = univesityName;
		this.universityAddress = universityAddress;
		this.directorName = directorName;
		this.phone = phone;
		this.EMail = EMail;
		this.web = web;
	}

	public Tbuniversities(String univesityName, String universityAddress,
			String directorName, String phone, String EMail, String web,
			List<Tbbranches> tbbrancheses,Set<User> tbstudentses,Set<Tbdepartment> tbdepartments) {
		this.univesityName = univesityName;
		this.universityAddress = universityAddress;
		this.directorName = directorName;
		this.phone = phone;
		this.EMail = EMail;
		this.web = web;
		this.tbbrancheses = tbbrancheses;		
		this.tbstudentses = tbstudentses;
		this.tbdepartments = tbdepartments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Univesity_name", nullable = false, length = 45)
	public String getUnivesityName() {
		return this.univesityName;
	}

	public void setUnivesityName(String univesityName) {
		this.univesityName = univesityName;
	}

	@Column(name = "University_address", nullable = false, length = 100)
	public String getUniversityAddress() {
		return this.universityAddress;
	}

	public void setUniversityAddress(String universityAddress) {
		this.universityAddress = universityAddress;
	}

	@Column(name = "Director_name", nullable = false, length = 45)
	public String getDirectorName() {
		return this.directorName;
	}

	public void setDirectorName(String directorName) {
		this.directorName = directorName;
	}

	@Column(name = "Phone", nullable = false, length = 30)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "Email",  length = 45)
	public String getEMail() {
		return this.EMail;
	}

	public void setEMail(String EMail) {
		this.EMail = EMail;
	}

	@Column(name = "Web", nullable = false, length = 45)
	public String getWeb() {
		return this.web;
	}

	public void setWeb(String web) {
		this.web = web;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbuniversities")
	@JsonBackReference
	public List<Tbbranches> getTbbrancheses() {
		return tbbrancheses;
	}

	public void setTbbrancheses(List<Tbbranches> tbbrancheses) {
		this.tbbrancheses = tbbrancheses;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbuniversities")
	@JsonManagedReference
	public Set<User> getTbstudentses() {
		return this.tbstudentses;
	}

	public void setTbstudentses(Set<User> tbstudentses) {
		this.tbstudentses = tbstudentses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbuniversities")
	@JsonManagedReference
	public Set<Tbdepartment> getTbdepartments() {
		return tbdepartments;
	}

	public void setTbdepartments(Set<Tbdepartment> tbdepartments) {
		this.tbdepartments = tbdepartments;
	}
	
	@Override
	public String toString(){
		return "{\"domain\":\"Tbuniversities\","+
				"\"id\":"+this.id+','+
				"\"univesityName\":\""+this.univesityName+"\","+
				"\"universityAddress\":\""+this.universityAddress+"\","+
				"\"directorName\":\""+this.directorName+"\","+
				"\"EMail\":\""+this.EMail+"\","+				
				"\"value\":\""+this.id+"\","+
				"\"text\":\""+this.univesityName+"\"}";
		
	}
	
	
/*	 @Override
	   public String toString()
	   {
	      return "Tbuniversities [id=" + id + ", univesityName=" + univesityName + ", " +
	            "universityAddress=" + universityAddress + ","+"directorName=" + directorName + ","+"phone=" + phone + ", "+"EMail=" + EMail + ", tbbrancheses=" + tbbrancheses.toString() + ", tbdepartments=" + tbdepartments + ", tbstudentses=" + tbstudentses + "]";
	   }*/	 

}
