package com.peace.users.model.mram;
// Generated Feb 24, 2016 1:13:58 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * DataGeoReport32 generated by hbm2java
 */
@Entity
@Table(name = "DATA_GEO_REPORT_3_2")
public class DataGeoReport32 implements java.io.Serializable {

	private Long explorationId;
	private Long id;
	private Integer dataIndex;
	private String data1;
	private String data2;
	private Integer data3;
	private Integer data4;
	private Integer data5;
	private Integer data6;
	private String data7;
	private Boolean istodotgol;

	public Boolean getIstodotgol() {
		return istodotgol;
	}


	public void setIstodotgol(Boolean istodotgol) {
		this.istodotgol = istodotgol;
	}
	public DataGeoReport32() {
	}

	public DataGeoReport32(Long explorationId, Long id) {
		this.explorationId = explorationId;
		this.id = id;
	}

	public DataGeoReport32(Long explorationId, Long id, Integer dataIndex, String data1, String data2,
			Integer data3, Integer data4, Integer data5, Integer data6, String data7) {
		this.explorationId = explorationId;
		this.id = id;
		this.dataIndex = dataIndex;
		this.data1 = data1;
		this.data2 = data2;
		this.data3 = data3;
		this.data4 = data4;
		this.data5 = data5;
		this.data6 = data6;
		this.data7 = data7;
	}

	@Id
	@SequenceGenerator(name="DATAGEOREPORT32_SEQ", sequenceName="DATAGEOREPORT32_SEQ", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="DATAGEOREPORT32_SEQ")
	@Column(name = "ID", nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	@Column(name = "EXPLORATION_ID", precision = 22, scale = 0)
	public Long getExplorationId() {
		return this.explorationId;
	}

	public void setExplorationId(Long explorationId) {
		this.explorationId = explorationId;
	}



	@Column(name = "DATA_INDEX", precision = 22, scale = 0)
	public Integer getDataIndex() {
		return this.dataIndex;
	}

	public void setDataIndex(Integer dataIndex) {
		this.dataIndex = dataIndex;
	}

	@Column(name = "DATA1")
	public String getData1() {
		return this.data1;
	}

	public void setData1(String data1) {
		this.data1 = data1;
	}

	@Column(name = "DATA2")
	public String getData2() {
		return this.data2;
	}

	public void setData2(String data2) {
		this.data2 = data2;
	}

	@Column(name = "DATA3", precision = 22, scale = 0)
	public Integer getData3() {
		return this.data3;
	}

	public void setData3(Integer data3) {
		this.data3 = data3;
	}

	@Column(name = "DATA4", precision = 22, scale = 0)
	public Integer getData4() {
		return this.data4;
	}

	public void setData4(Integer data4) {
		this.data4 = data4;
	}

	@Column(name = "DATA5", precision = 22, scale = 0)
	public Integer getData5() {
		return this.data5;
	}

	public void setData5(Integer data5) {
		this.data5 = data5;
	}

	@Column(name = "DATA6", precision = 22, scale = 0)
	public Integer getData6() {
		return this.data6;
	}

	public void setData6(Integer data6) {
		this.data6 = data6;
	}

	@Column(name = "DATA7")
	public String getData7() {
		return this.data7;
	}

	public void setData7(String data7) {
		this.data7 = data7;
	}

}
