package com.peace.users.model.mram;
// Generated Feb 25, 2016 4:45:04 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DataGeoForm8 generated by hbm2java
 */
@Entity
@Table(name = "DATA_GEO_FORM_8")
public class DataGeoForm8 implements java.io.Serializable {

	private Long id;
	private Long planid;
	private AnnualRegistration annualRegistration;
	private String data1;
	private String data2;
	private Integer data3;
	private Integer data4;
	private Integer data5;
	private Integer data6;
	private Integer data7;
	private Integer data8;

	public DataGeoForm8() {
	}

	public DataGeoForm8(Long id) {
		this.id = id;
	}

	public DataGeoForm8(Long id, AnnualRegistration annualRegistration, String data1, String data2,
			Integer data3, Integer data4, Integer data5, Integer data6, Integer data7,
			Integer data8) {
		this.id = id;
		this.annualRegistration = annualRegistration;
		this.data1 = data1;
		this.data2 = data2;
		this.data3 = data3;
		this.data4 = data4;
		this.data5 = data5;
		this.data6 = data6;
		this.data7 = data7;
		this.data8 = data8;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "PLANID")
	public Long getPlanid() {
		return planid;
	}

	public void setPlanid(Long planid) {
		this.planid = planid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PLANID", updatable=false, insertable=false,nullable=false)
	public AnnualRegistration getAnnualRegistration() {
		return this.annualRegistration;
	}

	public void setAnnualRegistration(AnnualRegistration annualRegistration) {
		this.annualRegistration = annualRegistration;
	}

	@Column(name = "DATA1")
	public String getData1() {
		return this.data1;
	}

	public void setData1(String data1) {
		this.data1 = data1;
	}

	@Column(name = "DATA2", length = 4000)
	public String getData2() {
		return this.data2;
	}

	public void setData2(String data2) {
		this.data2 = data2;
	}

	@Column(name = "DATA3", precision = 20, scale = 0)
	public Integer getData3() {
		return this.data3;
	}

	public void setData3(Integer data3) {
		this.data3 = data3;
	}

	@Column(name = "DATA4", precision = 20, scale = 0)
	public Integer getData4() {
		return this.data4;
	}

	public void setData4(Integer data4) {
		this.data4 = data4;
	}

	@Column(name = "DATA5", precision = 20, scale = 0)
	public Integer getData5() {
		return this.data5;
	}

	public void setData5(Integer data5) {
		this.data5 = data5;
	}

	@Column(name = "DATA6", precision = 20, scale = 0)
	public Integer getData6() {
		return this.data6;
	}

	public void setData6(Integer data6) {
		this.data6 = data6;
	}

	@Column(name = "DATA7", precision = 20, scale = 0)
	public Integer getData7() {
		return this.data7;
	}

	public void setData7(Integer data7) {
		this.data7 = data7;
	}

	@Column(name = "DATA8", precision = 20, scale = 0)
	public Integer getData8() {
		return this.data8;
	}

	public void setData8(Integer data8) {
		this.data8 = data8;
	}

}
