package com.peace.users.model.mram;
// Generated Mar 16, 2016 4:11:22 PM by Hibernate Tools 4.3.1.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.databind.jsonschema.JsonSerializableSchema;

/**
 * DataTezuMail generated by hbm2java
 */
@Entity
@Table(name = "DATA_TEZU_MAIL")
public class DataTezuMail implements java.io.Serializable {

	private Long id;
	private Long userid;
	private Long recipient;
	private Long licnum;
	private String recipientName;
	private String senderAvatar;
	private String sender;
	private String email;
	private String title;
	private String content;
	@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd HH:mm:ss")
	private String senddate;
	private String senderColor;
	private Boolean verified;
	private Boolean tezu;
	private LutUsers lutUsers;
	private List<LnkTezuData> lnkTezuDatas = new ArrayList<LnkTezuData>();

	public DataTezuMail() {
	}

	public DataTezuMail(Long id) {
		this.id = id;
	}

	public DataTezuMail(Long id, String senderAvatar, String sender, String email, String title, String content,
			String senddate, String senderColor, Boolean verified, List<LnkTezuData> lnkTezuDatas) {
		this.id = id;
		this.senderAvatar = senderAvatar;
		this.sender = sender;
		this.email = email;
		this.title = title;
		this.content = content;
		this.senddate = senddate;
		this.senderColor = senderColor;
		this.verified = verified;
		this.lnkTezuDatas = lnkTezuDatas;
	}

	@Id
	@SequenceGenerator(name="DATA_TEZU_MAIL_SEQ", sequenceName="DATA_TEZU_MAIL_SEQ", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="DATA_TEZU_MAIL_SEQ")
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "SENDER_AVATAR")
	public String getSenderAvatar() {
		return this.senderAvatar;
	}

	public void setSenderAvatar(String senderAvatar) {
		this.senderAvatar = senderAvatar;
	}
	
	@Column(name = "RECIPEINTNAME")
	public String getRecipientName() {
		return recipientName;
	}

	public void setRecipientName(String recipientName) {
		this.recipientName = recipientName;
	}

	@Column(name = "TEZU")
	public Boolean getTezu() {
		return tezu;
	}

	public void setTezu(Boolean tezu) {
		this.tezu = tezu;
	}

	@Column(name = "LICNUM")
	public Long getLicnum() {
		return licnum;
	}

	public void setLicnum(Long licnum) {
		this.licnum = licnum;
	}

	@Column(name = "RECIPEINT")
	public Long getRecipient() {
		return recipient;
	}

	public void setRecipient(Long recipient) {
		this.recipient = recipient;
	}

	@Column(name = "SENDER")
	public String getSender() {
		return this.sender;
	}

	public void setSender(String sender) {
		this.sender = sender;
	}

	@Column(name = "EMAIL")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "TITLE")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "CONTENT", length = 1000)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}


	@Column(name = "SENDDATE")
	public String getSenddate() {
		return senddate;
	}

	public void setSenddate(String special) {
		this.senddate = special;
	}
	
	

	@Column(name = "SENDER_COLOR")
	public String getSenderColor() {
		return this.senderColor;
	}

	

	public void setSenderColor(String senderColor) {
		this.senderColor = senderColor;
	}

	@Column(name = "VERIFIED")
	public Boolean getVerified() {
		return this.verified;
	}

	public void setVerified(Boolean verified) {
		this.verified = verified;
	}
	
	
	@Column(name = "USERID")
	public Long getUserid() {
		return userid;
	}

	public void setUserid(Long userid) {
		this.userid = userid;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USERID", nullable=false,insertable=false,updatable=false)
	@JsonBackReference
	public LutUsers getLutUsers() {
		return lutUsers;
	}

	public void setLutUsers(LutUsers lutUsers) {
		this.lutUsers = lutUsers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dataTezuMail")
	@JsonManagedReference
	public List<LnkTezuData> getLnkTezuDatas() {
		return this.lnkTezuDatas;
	}

	public void setLnkTezuDatas(List<LnkTezuData> lnkTezuDatas) {
		this.lnkTezuDatas = lnkTezuDatas;
	}

}
