package com.peace.users.model.mram;
// Generated Feb 28, 2016 2:07:34 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DataGeoReport7 generated by hbm2java
 */
@Entity
@Table(name = "DATA_GEO_REPORT_7")
public class DataGeoReport7 implements java.io.Serializable {

	private BigDecimal id;
	private BigDecimal explorationId;
	private BigDecimal parentIndex;
	private BigDecimal dataIndex;
	private String data1;
	private String data2;
	private String data3;
	private Date data4;
	private Date data5;
	private BigDecimal data6;
	private BigDecimal data7;
	private Boolean istodotgol;

	public Boolean getIstodotgol() {
		return istodotgol;
	}


	public void setIstodotgol(Boolean istodotgol) {
		this.istodotgol = istodotgol;
	}
	public DataGeoReport7() {
	}

	public DataGeoReport7(BigDecimal id, BigDecimal explorationId) {
		this.id = id;
		this.explorationId = explorationId;
	}

	public DataGeoReport7(BigDecimal id, BigDecimal explorationId, BigDecimal parentIndex, BigDecimal dataIndex,
			String data1, String data2, String data3, Date data4, Date data5, BigDecimal data6, BigDecimal data7) {
		this.id = id;
		this.explorationId = explorationId;
		this.parentIndex = parentIndex;
		this.dataIndex = dataIndex;
		this.data1 = data1;
		this.data2 = data2;
		this.data3 = data3;
		this.data4 = data4;
		this.data5 = data5;
		this.data6 = data6;
		this.data7 = data7;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "EXPLORATION_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getExplorationId() {
		return this.explorationId;
	}

	public void setExplorationId(BigDecimal explorationId) {
		this.explorationId = explorationId;
	}

	@Column(name = "PARENT_INDEX", precision = 22, scale = 0)
	public BigDecimal getParentIndex() {
		return this.parentIndex;
	}

	public void setParentIndex(BigDecimal parentIndex) {
		this.parentIndex = parentIndex;
	}

	@Column(name = "DATA_INDEX", precision = 22, scale = 0)
	public BigDecimal getDataIndex() {
		return this.dataIndex;
	}

	public void setDataIndex(BigDecimal dataIndex) {
		this.dataIndex = dataIndex;
	}

	@Column(name = "DATA1", length = 100)
	public String getData1() {
		return this.data1;
	}

	public void setData1(String data1) {
		this.data1 = data1;
	}

	@Column(name = "DATA2", length = 100)
	public String getData2() {
		return this.data2;
	}

	public void setData2(String data2) {
		this.data2 = data2;
	}

	@Column(name = "DATA3", length = 100)
	public String getData3() {
		return this.data3;
	}

	public void setData3(String data3) {
		this.data3 = data3;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATA4", length = 7)
	public Date getData4() {
		return this.data4;
	}

	public void setData4(Date data4) {
		this.data4 = data4;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATA5", length = 7)
	public Date getData5() {
		return this.data5;
	}

	public void setData5(Date data5) {
		this.data5 = data5;
	}

	@Column(name = "DATA6", precision = 22, scale = 0)
	public BigDecimal getData6() {
		return this.data6;
	}

	public void setData6(BigDecimal data6) {
		this.data6 = data6;
	}

	@Column(name = "DATA7", precision = 22, scale = 0)
	public BigDecimal getData7() {
		return this.data7;
	}

	public void setData7(BigDecimal data7) {
		this.data7 = data7;
	}

}
