package com.peace.users.model.mram;
// Generated Feb 29, 2016 11:55:26 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * DataForm17 generated by hbm2java
 */
@Entity
@Table(name = "DATA_FORM_17")
public class DataForm17 implements java.io.Serializable {

	private Long id;
	private Long planid;
	private AnnualRegistration annualRegistration;
	private String data1;
	private String data2;
	private Integer data3;
	private Integer data4;
	private Integer data5;
	private Integer data6;
	private Integer data7;
	private Integer data8;
	private Integer data9;
	private Integer data10;
	private Integer data11;
	private String data12;

	public DataForm17() {
	}

	public DataForm17(Long id) {
		this.id = id;
	}

	public DataForm17(Long id, AnnualRegistration annualRegistration, String data1, String data2,
			Integer data3, Integer data4, Integer data5, Integer data6, Integer data7, Integer data8,
			Integer data9, Integer data10, Integer data11, String data12) {
		this.id = id;
		this.annualRegistration = annualRegistration;
		this.data1 = data1;
		this.data2 = data2;
		this.data3 = data3;
		this.data4 = data4;
		this.data5 = data5;
		this.data6 = data6;
		this.data7 = data7;
		this.data8 = data8;
		this.data9 = data9;
		this.data10 = data10;
		this.data11 = data11;
		this.data12 = data12;
	}

	@Id
	@SequenceGenerator(name="DATA_FORM_17_SEQ", sequenceName="DATA_FORM_17_SEQ", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="DATA_FORM_17_SEQ")
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	@Column(name = "PLANID")
	public Long getPlanid() {
		return planid;
	}

	public void setPlanid(Long planid) {
		this.planid = planid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PLANID",insertable=false,updatable=false)
	public AnnualRegistration getAnnualRegistration() {
		return this.annualRegistration;
	}

	public void setAnnualRegistration(AnnualRegistration annualRegistration) {
		this.annualRegistration = annualRegistration;
	}

	@Column(name = "DATA1")
	public String getData1() {
		return this.data1;
	}

	public void setData1(String data1) {
		this.data1 = data1;
	}

	@Column(name = "DATA2", length = 500)
	public String getData2() {
		return this.data2;
	}

	public void setData2(String data2) {
		this.data2 = data2;
	}

	@Column(name = "DATA3", precision = 20, scale = 0)
	public Integer getData3() {
		return this.data3;
	}

	public void setData3(Integer data3) {
		this.data3 = data3;
	}

	@Column(name = "DATA4", precision = 20, scale = 0)
	public Integer getData4() {
		return this.data4;
	}

	public void setData4(Integer data4) {
		this.data4 = data4;
	}

	@Column(name = "DATA5", precision = 20, scale = 0)
	public Integer getData5() {
		return this.data5;
	}

	public void setData5(Integer data5) {
		this.data5 = data5;
	}

	@Column(name = "DATA6", precision = 20, scale = 0)
	public Integer getData6() {
		return this.data6;
	}

	public void setData6(Integer data6) {
		this.data6 = data6;
	}

	@Column(name = "DATA7", precision = 20, scale = 0)
	public Integer getData7() {
		return this.data7;
	}

	public void setData7(Integer data7) {
		this.data7 = data7;
	}

	@Column(name = "DATA8", precision = 20, scale = 0)
	public Integer getData8() {
		return this.data8;
	}

	public void setData8(Integer data8) {
		this.data8 = data8;
	}

	@Column(name = "DATA9", precision = 20, scale = 0)
	public Integer getData9() {
		return this.data9;
	}

	public void setData9(Integer data9) {
		this.data9 = data9;
	}

	@Column(name = "DATA10", precision = 20, scale = 0)
	public Integer getData10() {
		return this.data10;
	}

	public void setData10(Integer data10) {
		this.data10 = data10;
	}

	@Column(name = "DATA11", precision = 20, scale = 0)
	public Integer getData11() {
		return this.data11;
	}

	public void setData11(Integer data11) {
		this.data11 = data11;
	}

	@Column(name = "DATA12", length = 4000)
	public String getData12() {
		return this.data12;
	}

	public void setData12(String data12) {
		this.data12 = data12;
	}

}
