package com.peace.users.model.mram;
// Generated Mar 9, 2016 5:35:28 PM by Hibernate Tools 4.3.1.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * HelpCategory generated by hbm2java
 */
@Entity
@Table(name = "HELP_CATEGORY")
public class HelpCategory implements java.io.Serializable {

	private Long id;
	private Long cattype;
	private String catname;
	private List<HelpData> helpDatas = new ArrayList<HelpData>();

	public HelpCategory() {
	}

	public HelpCategory(Long id) {
		this.id = id;
	}

	public HelpCategory(Long id, Long cattype, String catname, List<HelpData> helpDatas) {
		this.id = id;
		this.cattype = cattype;
		this.catname = catname;
		this.helpDatas = helpDatas;
	}

	@Id
	@SequenceGenerator(name="HELP_CATEGORY_SEQ", sequenceName="HELP_CATEGORY_SEQ", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="HELP_CATEGORY_SEQ")
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "CATTYPE", precision = 22, scale = 0)
	public Long getCattype() {
		return this.cattype;
	}

	public void setCattype(Long cattype) {
		this.cattype = cattype;
	}

	@Column(name = "CATNAME", length = 500)
	public String getCatname() {
		return this.catname;
	}

	public void setCatname(String catname) {
		this.catname = catname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "helpCategory")
	@JsonBackReference
	public List<HelpData> getHelpDatas() {
		return this.helpDatas;
	}

	public void setHelpDatas(List<HelpData> helpDatas) {
		this.helpDatas = helpDatas;
	}

}
