package com.peace.users.model.mram;
// Generated Mar 9, 2016 5:35:28 PM by Hibernate Tools 4.3.1.Final

import java.sql.Clob;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * HelpData generated by hbm2java
 */
@Entity
@Table(name = "HELP_DATA")
public class HelpData implements java.io.Serializable {

	private Long id;
	private Long catid;
	private HelpCategory helpCategory;
	private String helptitle;
	private String helptext;

	public HelpData() {
	}

	public HelpData(Long id) {
		this.id = id;
	}

	public HelpData(Long id, HelpCategory helpCategory, String helptitle, String helptext) {
		this.id = id;
		this.helpCategory = helpCategory;
		this.helptitle = helptitle;
		this.helptext = helptext;
	}

	@Id
	@SequenceGenerator(name="HELP_DATA_SEQ", sequenceName="HELP_DATA_SEQ", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="HELP_DATA_SEQ")
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	
	@Column(name = "CATID")
	public Long getCatid() {
		return catid;
	}

	public void setCatid(Long catid) {
		this.catid = catid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CATID", nullable=false,insertable=false,updatable=false)
	@JsonBackReference
	public HelpCategory getHelpCategory() {
		return this.helpCategory;
	}

	public void setHelpCategory(HelpCategory helpCategory) {
		this.helpCategory = helpCategory;
	}

	@Column(name = "HELPTITLE", length = 500)
	public String getHelptitle() {
		return this.helptitle;
	}

	public void setHelptitle(String helptitle) {
		this.helptitle = helptitle;
	}

	@Column(name = "HELPTEXT")
	public String getHelptext() {
		return this.helptext;
	}

	public void setHelptext(String helptext) {
		this.helptext = helptext;
	}

}
