package com.peace.users.model.mram;
// Generated Nov 17, 2015 5:32:33 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LnkAppstepAppstatus generated by hbm2java
 */
@Entity
@Table(name = "LNK_APPSTEP_APPSTATUS")
public class LnkAppstepAppstatus implements java.io.Serializable {

	private LnkAppstepAppstatusId id;
	private LutAppstatus lutAppstatus;
	private LutAppsteps lutAppsteps;

	public LnkAppstepAppstatus() {
	}

	public LnkAppstepAppstatus(LnkAppstepAppstatusId id) {
		this.id = id;
	}

	public LnkAppstepAppstatus(LnkAppstepAppstatusId id, LutAppstatus lutAppstatus, LutAppsteps lutAppsteps) {
		this.id = id;
		this.lutAppstatus = lutAppstatus;
		this.lutAppsteps = lutAppsteps;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "linkId", column = @Column(name = "LinkID", nullable = false, precision = 22, scale = 0) ),
			@AttributeOverride(name = "statusId", column = @Column(name = "StatusID", precision = 22, scale = 0) ),
			@AttributeOverride(name = "stepsId", column = @Column(name = "StepsID", precision = 22, scale = 0) ) })
	public LnkAppstepAppstatusId getId() {
		return this.id;
	}

	public void setId(LnkAppstepAppstatusId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "StatusID", insertable = false, updatable = false)
	public LutAppstatus getLutAppstatus() {
		return this.lutAppstatus;
	}

	public void setLutAppstatus(LutAppstatus lutAppstatus) {
		this.lutAppstatus = lutAppstatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "StepsID", insertable = false, updatable = false)
	public LutAppsteps getLutAppsteps() {
		return this.lutAppsteps;
	}

	public void setLutAppsteps(LutAppsteps lutAppsteps) {
		this.lutAppsteps = lutAppsteps;
	}

}
