package com.peace.users.model.mram;
// Generated Nov 17, 2015 5:32:33 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LnkAppstepAppstatusId generated by hbm2java
 */
@Embeddable
public class LnkAppstepAppstatusId implements java.io.Serializable {

	private Integer linkId;
	private Integer statusId;
	private Integer stepsId;

	public LnkAppstepAppstatusId() {
	}

	public LnkAppstepAppstatusId(Integer linkId) {
		this.linkId = linkId;
	}

	public LnkAppstepAppstatusId(Integer linkId, Integer statusId, Integer stepsId) {
		this.linkId = linkId;
		this.statusId = statusId;
		this.stepsId = stepsId;
	}

	@Column(name = "LinkID", nullable = false, precision = 22, scale = 0)
	public Integer getLinkId() {
		return this.linkId;
	}

	public void setLinkId(Integer linkId) {
		this.linkId = linkId;
	}

	@Column(name = "StatusID", precision = 22, scale = 0)
	public Integer getStatusId() {
		return this.statusId;
	}

	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	@Column(name = "StepsID", precision = 22, scale = 0)
	public Integer getStepsId() {
		return this.stepsId;
	}

	public void setStepsId(Integer stepsId) {
		this.stepsId = stepsId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LnkAppstepAppstatusId))
			return false;
		LnkAppstepAppstatusId castOther = (LnkAppstepAppstatusId) other;

		return ((this.getLinkId() == castOther.getLinkId()) || (this.getLinkId() != null
				&& castOther.getLinkId() != null && this.getLinkId().equals(castOther.getLinkId())))
				&& ((this.getStatusId() == castOther.getStatusId()) || (this.getStatusId() != null
						&& castOther.getStatusId() != null && this.getStatusId().equals(castOther.getStatusId())))
				&& ((this.getStepsId() == castOther.getStepsId()) || (this.getStepsId() != null
						&& castOther.getStepsId() != null && this.getStepsId().equals(castOther.getStepsId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getLinkId() == null ? 0 : this.getLinkId().hashCode());
		result = 37 * result + (getStatusId() == null ? 0 : this.getStatusId().hashCode());
		result = 37 * result + (getStepsId() == null ? 0 : this.getStepsId().hashCode());
		return result;
	}

}
