package com.peace.users.model.mram;
// Generated Jan 10, 2016 2:07:49 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * LnkCommentMain generated by hbm2java
 */
@Entity
@Table(name = "LNK_COMMENT_MAIN")
public class LnkCommentMain implements java.io.Serializable {

	private Long id;
	private AnnualRegistration annualRegistration;
	private LutDecisions lutDecisions;
	private String mcomment;
	private Long userid;
	private Long planid;
	private Long desid;
	private String username;
	private String createdDate;
	private Long isgov;

	public LnkCommentMain() {
	}

	public LnkCommentMain(Long id) {
		this.id = id;
	}

	public LnkCommentMain(Long id, AnnualRegistration annualRegistration, String mcomment, Long userid,
			String username) {
		this.id = id;
		this.annualRegistration = annualRegistration;
		this.mcomment = mcomment;
		this.userid = userid;
		this.username = username;
	}

	@Id
	@SequenceGenerator(name="LNK_COMMENT_MAIN_SEQ", sequenceName="LNK_COMMENT_MAIN_SEQ", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="LNK_COMMENT_MAIN_SEQ")
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
		
	@Column(name = "ISGOV")
	public Long getIsgov() {
		return isgov;
	}

	public void setIsgov(Long isgov) {
		this.isgov = isgov;
	}

	@Column(name = "DESID", length = 4000)
	public Long getDesid() {
		return desid;
	}

	public void setDesid(Long desid) {
		this.desid = desid;
	}

	@Column(name = "PLANID", length = 4000)
	public Long getPlanid() {
		return planid;
	}

	public void setPlanid(Long planid) {
		this.planid = planid;
	}
	
	public String getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(String createdDate) {
		this.createdDate = createdDate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PLANID", nullable=false,insertable=false,updatable=false)
	public AnnualRegistration getAnnualRegistration() {
		return this.annualRegistration;
	}

	public void setAnnualRegistration(AnnualRegistration annualRegistration) {
		this.annualRegistration = annualRegistration;
	}
		
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DESID", nullable=false,insertable=false,updatable=false)
	public LutDecisions getLutDecisions() {
		return lutDecisions;
	}

	public void setLutDecisions(LutDecisions lutDecisions) {
		this.lutDecisions = lutDecisions;
	}

	@Column(name = "MCOMMENT", length = 4000)
	public String getMcomment() {
		return this.mcomment;
	}

	public void setMcomment(String mcomment) {
		this.mcomment = mcomment;
	}

	@Column(name = "USERID", precision = 22, scale = 0)
	public Long getUserid() {
		return this.userid;
	}

	public void setUserid(Long userid) {
		this.userid = userid;
	}

	@Column(name = "USERNAME", length = 400)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

}
