package com.peace.users.model.mram;
// Generated Nov 25, 2015 5:34:04 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LnkFormreporttype generated by hbm2java
 */
@Entity
@Table(name = "LNK_FORMREPORTTYPE")
public class LnkFormreporttype implements java.io.Serializable {

	private Integer id;
	private LutReporttype lutReporttype;
	private LutForms lutForms;
	private LutDivision lutDivision;

	public LnkFormreporttype() {
	}

	public LnkFormreporttype(Integer id) {
		this.id = id;
	}

	public LnkFormreporttype(Integer id, LutReporttype lutReporttype, LutForms lutForms, LutDivision lutDivision) {
		this.id = id;
		this.lutReporttype = lutReporttype;
		this.lutForms = lutForms;
		this.lutDivision = lutDivision;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REPORTTYPEID")
	public LutReporttype getLutReporttype() {
		return this.lutReporttype;
	}

	public void setLutReporttype(LutReporttype lutReporttype) {
		this.lutReporttype = lutReporttype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FORMID")
	public LutForms getLutForms() {
		return this.lutForms;
	}

	public void setLutForms(LutForms lutForms) {
		this.lutForms = lutForms;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DIVISIONID")
	public LutDivision getLutDivision() {
		return this.lutDivision;
	}

	public void setLutDivision(LutDivision lutDivision) {
		this.lutDivision = lutDivision;
	}

}
