package com.peace.users.model.mram;
// Generated Feb 4, 2016 6:23:07 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LnkLicProduct generated by hbm2java
 */
@Entity
@Table(name = "LNK_LIC_PRODUCT")
public class LnkLicProduct implements java.io.Serializable {

	private Long id;
	private LutProducts lutProducts;
	private LnkLicenseConfig lnkLicenseConfig;
	private Set<LnkMproSubpro> lnkMproSubpros = new HashSet<LnkMproSubpro>(0);

	public LnkLicProduct() {
	}

	public LnkLicProduct(Long id) {
		this.id = id;
	}

	public LnkLicProduct(Long id, LutProducts lutProducts, LnkLicenseConfig lnkLicenseConfig,
			Set<LnkMproSubpro> lnkMproSubpros) {
		this.id = id;
		this.lutProducts = lutProducts;
		this.lnkLicenseConfig = lnkLicenseConfig;
		this.lnkMproSubpros = lnkMproSubpros;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROID")
	public LutProducts getLutProducts() {
		return this.lutProducts;
	}

	public void setLutProducts(LutProducts lutProducts) {
		this.lutProducts = lutProducts;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LICNUM")
	public LnkLicenseConfig getLnkLicenseConfig() {
		return this.lnkLicenseConfig;
	}

	public void setLnkLicenseConfig(LnkLicenseConfig lnkLicenseConfig) {
		this.lnkLicenseConfig = lnkLicenseConfig;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lnkLicProduct")
	public Set<LnkMproSubpro> getLnkMproSubpros() {
		return this.lnkMproSubpros;
	}

	public void setLnkMproSubpros(Set<LnkMproSubpro> lnkMproSubpros) {
		this.lnkMproSubpros = lnkMproSubpros;
	}

}
