package com.peace.users.model.mram;
// Generated Feb 4, 2016 6:23:07 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LnkMproSubpro generated by hbm2java
 */
@Entity
@Table(name = "LNK_MPRO_SUBPRO")
public class LnkMproSubpro implements java.io.Serializable {

	private Long id;
	private LutSubProduct lutSubProduct;
	private LnkLicProduct lnkLicProduct;

	public LnkMproSubpro() {
	}

	public LnkMproSubpro(Long id) {
		this.id = id;
	}

	public LnkMproSubpro(Long id, LutSubProduct lutSubProduct, LnkLicProduct lnkLicProduct) {
		this.id = id;
		this.lutSubProduct = lutSubProduct;
		this.lnkLicProduct = lnkLicProduct;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SPROID")
	public LutSubProduct getLutSubProduct() {
		return this.lutSubProduct;
	}

	public void setLutSubProduct(LutSubProduct lutSubProduct) {
		this.lutSubProduct = lutSubProduct;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MPROID")
	public LnkLicProduct getLnkLicProduct() {
		return this.lnkLicProduct;
	}

	public void setLnkLicProduct(LnkLicProduct lnkLicProduct) {
		this.lnkLicProduct = lnkLicProduct;
	}

}
