package com.peace.users.model.mram;
// Generated Nov 17, 2015 5:32:33 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OrderBy;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * LnkMenuRole generated by hbm2java
 */
@Entity
@Table(name = "LNK_MENU_ROLE")
public class LnkMenuRole implements java.io.Serializable {

	private Long id;
	private Long roleid;
	private Long menuid;
	private LutRole lutRole;
	private LutMenu lutMenu;
	private Long rcreate;
	private Long rread;
	private Long rupdate;
	private Long rdelete;
	private Long rexport;
	private Long orderid;

	public LnkMenuRole() {
	}

	public LnkMenuRole(Long id) {
		this.id = id;
	}

	public LnkMenuRole(Long id, LutRole lutRole, LutMenu lutMenu, Long rcreate, Long rread,
			Long rupdate, Long rdelete, Long rexport) {
		this.id = id;
		this.lutRole = lutRole;
		this.lutMenu = lutMenu;
		this.rcreate = rcreate;
		this.rread = rread;
		this.rupdate = rupdate;
		this.rdelete = rdelete;
		this.rexport = rexport;
	}

	@Id
	@SequenceGenerator(name="LNK_MENU_ROLE_SEQ", sequenceName="LNK_MENU_ROLE_SEQ", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="LNK_MENU_ROLE_SEQ")
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id",nullable = false,insertable=false,updatable=false)
	@OrderBy("ID")
	public LutRole getLutRole() {
		return this.lutRole;
	}

	public void setLutRole(LutRole lutRole) {
		this.lutRole = lutRole;
	}
	
	
	@Column(name = "role_id")
	public Long getRoleid() {
		return roleid;
	}

	public void setRoleid(Long roleid) {
		this.roleid = roleid;
	}
		
	@Column(name = "menu_id")
	public Long getMenuid() {
		return menuid;
	}

	public void setMenuid(Long menuid) {
		this.menuid = menuid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "menu_id",nullable = false,insertable=false,updatable=false)
	@OrderBy("ID")
	public LutMenu getLutMenu() {
		return this.lutMenu;
	}

	public void setLutMenu(LutMenu lutMenu) {
		this.lutMenu = lutMenu;
	}

	@Column(name = "rcreate", precision = 22, scale = 0)
	public Long getRcreate() {
		return this.rcreate;
	}

	public void setRcreate(Long rcreate) {
		this.rcreate = rcreate;
	}

	@Column(name = "rread", precision = 22, scale = 0)
	public Long getRread() {
		return this.rread;
	}

	public void setRread(Long rread) {
		this.rread = rread;
	}

	@Column(name = "rupdate", precision = 22, scale = 0)
	public Long getRupdate() {
		return this.rupdate;
	}

	public void setRupdate(Long rupdate) {
		this.rupdate = rupdate;
	}

	@Column(name = "rdelete", precision = 22, scale = 0)
	public Long getRdelete() {
		return this.rdelete;
	}

	public void setRdelete(Long rdelete) {
		this.rdelete = rdelete;
	}

	@Column(name = "rexport", precision = 22, scale = 0)
	public Long getRexport() {
		return this.rexport;
	}

	public void setRexport(Long rexport) {
		this.rexport = rexport;
	}

	@Column(name = "ORDERID", precision = 22, scale = 0)
	public Long getOrderid() {
		return orderid;
	}

	public void setOrderid(Long orderid) {
		this.orderid = orderid;
	}
	
	

}
