package com.peace.users.model.mram;
// Generated Jan 5, 2016 12:17:50 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * LnkPlanTab generated by hbm2java
 */
@Entity
@Table(name = "LNK_PLAN_TAB")
public class LnkPlanTab implements java.io.Serializable {

	private Long id;
	private Long planid;
	private Integer tabid;
	private AnnualRegistration annualRegistration;
	
	public LnkPlanTab() {
	}

	public LnkPlanTab(Long id) {
		this.id = id;
	}

	public LnkPlanTab(Long id, Long planid, Integer tabid) {
		this.id = id;
		this.planid = planid;
		this.tabid = tabid;
	}

	@Id
	@SequenceGenerator(name="LNK_PLAN_TAB_SEQ", sequenceName="LNK_PLAN_TAB_SEQ", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="LNK_PLAN_TAB_SEQ")	
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "PLANID", precision = 22, scale = 0)
	public Long getPlanid() {
		return this.planid;
	}

	public void setPlanid(Long planid) {
		this.planid = planid;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PLANID",nullable=false,insertable=false,updatable=false)
	public AnnualRegistration getAnnualRegistration() {
		return this.annualRegistration;
	}

	public void setAnnualRegistration(AnnualRegistration annualRegistration) {
		this.annualRegistration = annualRegistration;
	}

	@Column(name = "TABID", precision = 22, scale = 0)
	public Integer getTabid() {
		return this.tabid;
	}

	public void setTabid(Integer tabid) {
		this.tabid = tabid;
	}

}
