package com.peace.users.model.mram;
// Generated Dec 21, 2015 11:52:06 AM by Hibernate Tools 4.3.1.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * LnkPlanAttachedFiles generated by hbm2java
 */
@Entity
@Table(name = "LNK_PLAN_ATTACHED_FILES")
public class LnkPlanAttachedFiles implements java.io.Serializable {

	private Long id;
	private AnnualRegistration annualRegistration;
	private LutFormNotes lutFormNotes;
	//private LnkPlanNotes lnkPlanNotes;
	private Long noteid;
	private String lpReg;
	private String attachfiletype;
	private String atdate;
	private String filename;
	private String fileext;
	private long expid;
	private Boolean istodotgol;
	
	private List<LnkComment> LnkCommentes =  new ArrayList<LnkComment>();
	
	public LnkPlanAttachedFiles() {
		this.istodotgol = false;
	}

	public LnkPlanAttachedFiles(Long id) {
		this.id = id;
	}

	public LnkPlanAttachedFiles(Long id, AnnualRegistration annualRegistration, String lpReg,
			String attachfiletype) {
		this.id = id;
		this.annualRegistration = annualRegistration;
		this.lpReg = lpReg;
		this.attachfiletype = attachfiletype;
	}

	@Id
	@SequenceGenerator(name="PLAN_ATTACHED_FILES_SEQ", sequenceName="PLAN_ATTACHED_FILES_SEQ", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="PLAN_ATTACHED_FILES_SEQ")
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "EXPPLANID", length = 20)
	public long getExpid() {
		return expid;
	}

	public void setExpid(long expid) {
		this.expid = expid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JsonBackReference
	@JoinColumn(name = "EXPPLANID", nullable=false,insertable=false,updatable=false)
	public AnnualRegistration getAnnualRegistration() {
		return this.annualRegistration;
	}

	public void setAnnualRegistration(AnnualRegistration annualRegistration) {
		this.annualRegistration = annualRegistration;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JsonBackReference
	@JoinColumn(name = "NOTEID", nullable=false,insertable=false,updatable=false)
	public LutFormNotes getLutFormNotes() {
		return lutFormNotes;
	}

	public void setLutFormNotes(LutFormNotes lutFormNotes) {
		this.lutFormNotes = lutFormNotes;
	}
	
	
	
	
	@Column(name = "NOTEID", length = 20)
	public Long getNoteid() {
		return noteid;
	}

	public void setNoteid(Long noteid) {
		this.noteid = noteid;
	}
	
	
	@Column(name = "FILEEXT", length = 250)
	public String getFileext() {
		return fileext;
	}

	public void setFileext(String fileext) {
		this.fileext = fileext;
	}

	@Column(name = "FILENAME", length = 250)
	public String getFilename() {
		return filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Column(name = "ATDATE", length = 250)
	public String getAtdate() {
		return atdate;
	}

	public void setAtdate(String atdate) {
		this.atdate = atdate;
	}

	@Column(name = "LP_REG", length = 7)
	public String getLpReg() {
		return this.lpReg;
	}	

	public void setLpReg(String lpReg) {
		this.lpReg = lpReg;
	}

	@Column(name = "ATTACHFILETYPE")
	public String getAttachfiletype() {
		return this.attachfiletype;
	}

	public void setAttachfiletype(String attachfiletype) {
		this.attachfiletype = attachfiletype;
	}

	public Boolean getIstodotgol() {
		return istodotgol;
	}

	public void setIstodotgol(Boolean istodotgol) {
		this.istodotgol = istodotgol;
	}

/*	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lutFormNotes")
	@JsonBackReference
	public List<LnkComment> getLnkCommentes() {
		return LnkCommentes;
	}

	public void setLnkCommentes(List<LnkComment> lnkCommentes) {
		LnkCommentes = lnkCommentes;
	}*/
	
}
