package com.peace.users.model.mram;
// Generated Dec 21, 2015 11:52:06 AM by Hibernate Tools 4.3.1.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * LnkPlanAttachedFiles generated by hbm2java
 */
@Entity
@Table(name = "LNK_PLAN_ZERO_ATTACHMENTS")
public class LnkPlanZeroAttachments implements java.io.Serializable {

	private Long id;
	private AnnualRegistration annualRegistration;
	private Long noteid;
	private String atturl;
	private String atdate;
	private String filename;
	private String fileext;
	private long planid;
	
	public LnkPlanZeroAttachments() {
	}

	@Id
	@SequenceGenerator(name="LNK_PLAN_ZERO_ATTACHMENTS_SEQ", sequenceName="LNK_PLAN_ZERO_ATTACHMENTS_SEQ", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="LNK_PLAN_ZERO_ATTACHMENTS_SEQ")
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JsonBackReference
	@JoinColumn(name = "PLANID", nullable=false,insertable=false,updatable=false)
	public AnnualRegistration getAnnualRegistration() {
		return this.annualRegistration;
	}

	public void setAnnualRegistration(AnnualRegistration annualRegistration) {
		this.annualRegistration = annualRegistration;
	}
	
	@Column(name = "NOTEID", length = 20)
	public Long getNoteid() {
		return noteid;
	}

	public void setNoteid(Long noteid) {
		this.noteid = noteid;
	}
	
	@Column(name = "FILEEXT", length = 250)
	public String getFileext() {
		return fileext;
	}

	public void setFileext(String fileext) {
		this.fileext = fileext;
	}

	@Column(name = "FILENAME", length = 250)
	public String getFilename() {
		return filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Column(name = "ATDATE", length = 250)
	public String getAtdate() {
		return atdate;
	}

	public void setAtdate(String atdate) {
		this.atdate = atdate;
	}

	public String getAtturl() {
		return atturl;
	}

	public void setAtturl(String atturl) {
		this.atturl = atturl;
	}

	public long getPlanid() {
		return planid;
	}

	public void setPlanid(long planid) {
		this.planid = planid;
	}
	
}
