package com.peace.users.model.mram;
// Generated Feb 18, 2016 1:59:45 PM by Hibernate Tools 4.3.1.Final

import java.sql.Clob;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * LnkReqAnn generated by hbm2java
 */
@Entity
@Table(name = "LNK_REQ_ANN")
public class LnkReqAnn implements java.io.Serializable {

	private Long id;
	private RegReportReq regReportReq;
	private String horde;
	private String aimagid;
	private String sumid;
	private Long mineralid;
	private Long deposidid;
	private String countries;
	private String appdate;
	private Long yearcapacity;
	private Long workyear;
	private Long minetypeid;
	private Long komissid;
	private Long reqid;
	private String komissdate;
	private String komissakt;
	private String startdate;
	private Long bombid;
	private Long bombtype;
	private String concetrate;
	private Long statebudgetid;
	
	private int cyear;
	private int ismatter;
	private int isconcetrate;
	private int isexplosion;
	
	private List<SubContract> subContracts = new ArrayList<SubContract>();
	private List<SubNoContract> subNoContracts = new ArrayList<SubNoContract>(0);

	public LnkReqAnn() {
	}

	public LnkReqAnn(Long id) {
		this.id = id;
	}

	public LnkReqAnn(Long id, RegReportReq regReportReq, String aimagid, String sumid,
			Long mineralid, Long deposidid, String countries, String appdate, Long yearcapacity,
			Long workyear, Long minetypeid, Long komissid, String komissdate, String komissakt,
			String startdate, Long bombid, Long bombtype, String concetrate, Long statebudgetid) {
		this.id = id;
		this.regReportReq = regReportReq;
		this.aimagid = aimagid;
		this.sumid = sumid;
		this.mineralid = mineralid;
		this.deposidid = deposidid;
		this.countries = countries;
		this.appdate = appdate;
		this.yearcapacity = yearcapacity;
		this.workyear = workyear;
		this.minetypeid = minetypeid;
		this.komissid = komissid;
		this.komissdate = komissdate;
		this.komissakt = komissakt;
		this.startdate = startdate;
		this.bombid = bombid;
		this.bombtype = bombtype;
		this.concetrate = concetrate;
		this.statebudgetid = statebudgetid;
	}

	@Id
	@SequenceGenerator(name="LNK_REQ_ANN_SEQ", sequenceName="LNK_REQ_ANN_SEQ", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="LNK_REQ_ANN_SEQ")
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	
	@Column(name = "HORDE")	
	public String getHorde() {
		return horde;
	}

	public void setHorde(String horde) {
		this.horde = horde;
	}
	
	@Column(name = "CYEAR")	
	public int getCyear() {
		return cyear;
	}

	public void setCyear(int cyear) {
		this.cyear = cyear;
	}

	@Column(name = "ISMATTER")	
	public int getIsmatter() {
		return ismatter;
	}

	public void setIsmatter(int ismatter) {
		this.ismatter = ismatter;
	}
	
	@Column(name = "ISCONCENTRATE")	
	public int getIsconcetrate() {
		return isconcetrate;
	}

	public void setIsconcetrate(int isconcetrate) {
		this.isconcetrate = isconcetrate;
	}

	@Column(name = "ISEXPLOSION")	
	public int getIsexplosion() {
		return isexplosion;
	}

	public void setIsexplosion(int isexplosion) {
		this.isexplosion = isexplosion;
	}

	@Column(name = "REQID")
	public Long getReqid() {
		return reqid;
	}

	public void setReqid(Long reqid) {
		this.reqid = reqid;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REQID", nullable=false,insertable=false,updatable=false)
	@JsonBackReference
	public RegReportReq getRegReportReq() {
		return this.regReportReq;
	}

	public void setRegReportReq(RegReportReq regReportReq) {
		this.regReportReq = regReportReq;
	}

	@Column(name = "AIMAGID")
	public String getAimagid() {
		return this.aimagid;
	}

	public void setAimagid(String aimagid) {
		this.aimagid = aimagid;
	}

	@Column(name = "SUMID")
	public String getSumid() {
		return this.sumid;
	}

	public void setSumid(String sumid) {
		this.sumid = sumid;
	}

	@Column(name = "MINERALID", precision = 22, scale = 0)
	public Long getMineralid() {
		return this.mineralid;
	}

	public void setMineralid(Long mineralid) {
		this.mineralid = mineralid;
	}

	@Column(name = "DEPOSIDID", precision = 22, scale = 0)
	public Long getDeposidid() {
		return this.deposidid;
	}

	public void setDeposidid(Long deposidid) {
		this.deposidid = deposidid;
	}

	@Column(name = "COUNTRIES", length = 500)
	public String getCountries() {
		return this.countries;
	}

	public void setCountries(String countries) {
		this.countries = countries;
	}

	@Column(name = "APPDATE", length = 100)
	public String getAppdate() {
		return this.appdate;
	}

	public void setAppdate(String appdate) {
		this.appdate = appdate;
	}

	@Column(name = "YEARCAPACITY")
	public Long getYearcapacity() {
		return this.yearcapacity;
	}

	public void setYearcapacity(Long yearcapacity) {
		this.yearcapacity = yearcapacity;
	}

	@Column(name = "WORKYEAR")
	public Long getWorkyear() {
		return this.workyear;
	}

	public void setWorkyear(Long workyear) {
		this.workyear = workyear;
	}

	@Column(name = "MINETYPEID", precision = 22, scale = 0)
	public Long getMinetypeid() {
		return this.minetypeid;
	}

	public void setMinetypeid(Long minetypeid) {
		this.minetypeid = minetypeid;
	}

	@Column(name = "KOMISSID", precision = 22, scale = 0)
	public Long getKomissid() {
		return this.komissid;
	}

	public void setKomissid(Long komissid) {
		this.komissid = komissid;
	}

	@Column(name = "KOMISSDATE", length = 50)
	public String getKomissdate() {
		return this.komissdate;
	}

	public void setKomissdate(String komissdate) {
		this.komissdate = komissdate;
	}

	@Column(name = "KOMISSAKT")
	public String getKomissakt() {
		return this.komissakt;
	}

	public void setKomissakt(String komissakt) {
		this.komissakt = komissakt;
	}

	@Column(name = "STARTDATE", length = 50)
	public String getStartdate() {
		return this.startdate;
	}

	public void setStartdate(String startdate) {
		this.startdate = startdate;
	}

	@Column(name = "BOMBID", precision = 22, scale = 0)
	public Long getBombid() {
		return this.bombid;
	}

	public void setBombid(Long bombid) {
		this.bombid = bombid;
	}

	@Column(name = "BOMBTYPE", precision = 22, scale = 0)
	public Long getBombtype() {
		return this.bombtype;
	}

	public void setBombtype(Long bombtype) {
		this.bombtype = bombtype;
	}

	@Column(name = "CONCETRATE")
	public String getConcetrate() {
		return this.concetrate;
	}

	public void setConcetrate(String concetrate) {
		this.concetrate = concetrate;
	}

	@Column(name = "STATEBUDGETID", precision = 22, scale = 0)
	public Long getStatebudgetid() {
		return this.statebudgetid;
	}

	public void setStatebudgetid(Long statebudgetid) {
		this.statebudgetid = statebudgetid;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lnkReqAnn")
	public List<SubContract> getSubContracts() {
		return this.subContracts;
	}

	public void setSubContracts(List<SubContract> subContracts) {
		this.subContracts = subContracts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lnkReqAnn")
	public List<SubNoContract> getSubNoContracts() {
		return this.subNoContracts;
	}

	public void setSubNoContracts(List<SubNoContract> subNoContracts) {
		this.subNoContracts = subNoContracts;
	}
}
