package com.peace.users.model.mram;
// Generated Nov 17, 2015 5:32:33 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * LnkReportRegBunl generated by hbm2java
 */
@Entity
@Table(name = "LNK_REPORT_REG_BUNL")
public class LnkReportRegBunl implements java.io.Serializable {

	private Long id;
	private String bundledLicenseNum;
	private RegReportReq regReportReq;	
	private String addBunLicenseNum;


	@Id
	@SequenceGenerator(name="LUT_ROLE_SEQ", sequenceName="LUT_ROLE_SEQ", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="LUT_ROLE_SEQ")	
	@Column(name = "ID", nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	@Column(name = "BundledLicenseNum",  nullable = false, length = 10)
	public String getBundledLicenseNum() {
		return this.bundledLicenseNum;
	}

	public void setBundledLicenseNum(String bundledLicenseNum) {
		this.bundledLicenseNum = bundledLicenseNum;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BundledLicenseNum", nullable = false,insertable=false,updatable=false)
	@JsonBackReference
	public RegReportReq getRegReportReq() {
		return this.regReportReq;
	}

	public void setRegReportReq(RegReportReq regReportReq) {
		this.regReportReq = regReportReq;
	}



	@Column(name = "ADD_BunLicenseNum", nullable = false, length = 10)
	public String getAddBunLicenseNum() {
		return this.addBunLicenseNum;
	}

	public void setAddBunLicenseNum(String addBunLicenseNum) {
		this.addBunLicenseNum = addBunLicenseNum;
	}

	@Override
	public String toString(){
		return "{\"rexport\":\""+this.addBunLicenseNum+"\"}";
		
	}
}
