package com.peace.users.model.mram;
// Generated Feb 20, 2016 3:53:28 PM by Hibernate Tools 4.3.1.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * LnkReqPv generated by hbm2java
 */
@Entity
@Table(name = "LNK_REQ_PV")
public class LnkReqPv implements java.io.Serializable {

	private Long id;
	private RegReportReq regReportReq;
	private String factoryname;
	private Long aimagid;
	private Long sumid;
	private Long reqid;
	private String invcountry;
	private Long invperccent;
	private String tezuappdate;
	private String tezulp;
	private Long tezupower;
	private Long workyear;
	private String startdate;
	private String rawmine;

	public LnkReqPv() {
	}

	public LnkReqPv(Long id) {
		this.id = id;
	}

	public LnkReqPv(Long id, RegReportReq regReportReq, String factoryname, Long aimagid, Long sumid,
			String invcountry, Long invperccent, String tezuappdate, String tezulp, Long tezupower, Long workyear,
			String startdate, String rawmine) {
		this.id = id;
		this.regReportReq = regReportReq;
		this.factoryname = factoryname;
		this.aimagid = aimagid;
		this.sumid = sumid;
		this.invcountry = invcountry;
		this.invperccent = invperccent;
		this.tezuappdate = tezuappdate;
		this.tezulp = tezulp;
		this.tezupower = tezupower;
		this.workyear = workyear;
		this.startdate = startdate;
		this.rawmine = rawmine;
	}

	@Id
	@SequenceGenerator(name="LNK_REQ_PV_SEQ", sequenceName="LNK_REQ_PV_SEQ", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="LNK_REQ_PV_SEQ")
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	
	
	@Column(name = "REQID")
	public Long getReqid() {
		return reqid;
	}

	public void setReqid(Long reqid) {
		this.reqid = reqid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REQID",nullable=false,insertable=false,updatable=false)
	@JsonBackReference
	public RegReportReq getRegReportReq() {
		return this.regReportReq;
	}

	public void setRegReportReq(RegReportReq regReportReq) {
		this.regReportReq = regReportReq;
	}

	@Column(name = "FACTORYNAME")
	public String getFactoryname() {
		return this.factoryname;
	}

	public void setFactoryname(String factoryname) {
		this.factoryname = factoryname;
	}

	@Column(name = "AIMAGID", precision = 22, scale = 0)
	public Long getAimagid() {
		return this.aimagid;
	}

	public void setAimagid(Long aimagid) {
		this.aimagid = aimagid;
	}

	@Column(name = "SUMID", precision = 22, scale = 0)
	public Long getSumid() {
		return this.sumid;
	}

	public void setSumid(Long sumid) {
		this.sumid = sumid;
	}

	@Column(name = "INVCOUNTRY")
	public String getInvcountry() {
		return this.invcountry;
	}

	public void setInvcountry(String invcountry) {
		this.invcountry = invcountry;
	}

	@Column(name = "INVPERCCENT")
	public Long getInvperccent() {
		return this.invperccent;
	}

	public void setInvperccent(Long invperccent) {
		this.invperccent = invperccent;
	}

	@Column(name = "TEZUAPPDATE", length = 50)
	public String getTezuappdate() {
		return this.tezuappdate;
	}

	public void setTezuappdate(String tezuappdate) {
		this.tezuappdate = tezuappdate;
	}

	@Column(name = "TEZULP")
	public String getTezulp() {
		return this.tezulp;
	}

	public void setTezulp(String tezulp) {
		this.tezulp = tezulp;
	}

	@Column(name = "TEZUPOWER")
	public Long getTezupower() {
		return this.tezupower;
	}

	public void setTezupower(Long tezupower) {
		this.tezupower = tezupower;
	}

	@Column(name = "WORKYEAR")
	public Long getWorkyear() {
		return this.workyear;
	}

	public void setWorkyear(Long workyear) {
		this.workyear = workyear;
	}

	@Column(name = "STARTDATE", length = 50)
	public String getStartdate() {
		return this.startdate;
	}

	public void setStartdate(String startdate) {
		this.startdate = startdate;
	}

	@Column(name = "RAWMINE")
	public String getRawmine() {
		return this.rawmine;
	}

	public void setRawmine(String rawmine) {
		this.rawmine = rawmine;
	}

}
