package com.peace.users.model.mram;
// Generated Nov 17, 2015 5:32:33 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * LnkRoleAuth generated by hbm2java
 */
@Entity
@Table(name = "LNK_ROLE_AUTH")
public class LnkRoleAuth implements java.io.Serializable {

	private Long id;
	private LutRole lutRole;
	private Long roleid;
	private String authName;

	public LnkRoleAuth() {
	}

	public LnkRoleAuth(Long id) {
		this.id = id;
	}

	public LnkRoleAuth(Long id, LutRole lutRole, String authName) {
		this.id = id;
		this.lutRole = lutRole;
		this.authName = authName;
	}

	@Id
	@SequenceGenerator(name="LNK_ROLE_AUTH_SEQ", sequenceName="LNK_ROLE_AUTH_SEQ")
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="LNK_ROLE_AUTH_SEQ")
	@Column(name = "id", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	
	@Column(name = "role_id")
	public Long getRoleid() {
		return roleid;
	}

	public void setRoleid(Long roleid) {
		this.roleid = roleid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id", nullable=false,insertable=false,updatable=false)
	public LutRole getLutRole() {
		return this.lutRole;
	}

	public void setLutRole(LutRole lutRole) {
		this.lutRole = lutRole;
	}

	@Column(name = "auth_name")
	public String getAuthName() {
		return this.authName;
	}

	public void setAuthName(String authName) {
		this.authName = authName;
	}

}
