package com.peace.users.model.mram;
// Generated Mar 16, 2016 4:11:22 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * LnkTezuData generated by hbm2java
 */
@Entity
@Table(name = "LNK_TEZU_DATA")
public class LnkTezuData implements java.io.Serializable {

	private Long id;
	private Long tezuid;
	private DataTezuMail dataTezuMail;
	private String filename;
	private String filesize;
	private String filetype;
	private String fileUrl;
	public LnkTezuData() {
	}

	public LnkTezuData(Long id) {
		this.id = id;
	}

	public LnkTezuData(Long id, DataTezuMail dataTezuMail, String filename, String filesize, String filetype) {
		this.id = id;
		this.dataTezuMail = dataTezuMail;
		this.filename = filename;
		this.filesize = filesize;
		this.filetype = filetype;
	}

	@Id
	@SequenceGenerator(name="LNK_TEZU_SEQ", sequenceName="LNK_TEZU_SEQ", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="LNK_TEZU_SEQ")
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	@Column(name = "TEZUID")
	public Long getTezuid() {
		return tezuid;
	}

	public void setTezuid(Long tezuid) {
		this.tezuid = tezuid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TEZUID",nullable=false,insertable=false,updatable=false)
	@JsonBackReference
	public DataTezuMail getDataTezuMail() {
		return this.dataTezuMail;
	}

	public void setDataTezuMail(DataTezuMail dataTezuMail) {
		this.dataTezuMail = dataTezuMail;
	}

	@Column(name = "FILENAME")
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}
		
	@Column(name = "FILEURL")
	public String getFileUrl() {
		return fileUrl;
	}

	public void setFileUrl(String fileUrl) {
		this.fileUrl = fileUrl;
	}

	@Column(name = "FILESIZE")
	public String getFilesize() {
		return this.filesize;
	}

	public void setFilesize(String filesize) {
		this.filesize = filesize;
	}

	@Column(name = "FILETYPE")
	public String getFiletype() {
		return this.filetype;
	}

	public void setFiletype(String filetype) {
		this.filetype = filetype;
	}

}
