package com.peace.users.model.mram;
// Generated Feb 17, 2016 12:00:21 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LnkWeeklyProduct generated by hbm2java
 */
@Entity
@Table(name = "LNK_WEEKLY_PRODUCT")
public class LnkWeeklyProduct implements java.io.Serializable {

	private Long id;
	private LutProducts lutProducts;
	private RegReportReq regReportReq;

	public LnkWeeklyProduct() {
	}

	public LnkWeeklyProduct(Long id) {
		this.id = id;
	}

	public LnkWeeklyProduct(Long id, LutProducts lutProducts, RegReportReq regReportReq) {
		this.id = id;
		this.lutProducts = lutProducts;
		this.regReportReq = regReportReq;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROID")
	public LutProducts getLutProducts() {
		return this.lutProducts;
	}

	public void setLutProducts(LutProducts lutProducts) {
		this.lutProducts = lutProducts;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REQID")
	public RegReportReq getRegReportReq() {
		return this.regReportReq;
	}

	public void setRegReportReq(RegReportReq regReportReq) {
		this.regReportReq = regReportReq;
	}

}
