package com.peace.users.model.mram;
// Generated Feb 1, 2016 8:06:02 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * LnkWeeklyCountry generated by hbm2java
 */
@Entity
@Table(name = "LNK_WEEKLY_COUNTRY")
public class LnkWeeklyCountry implements java.io.Serializable {

	private Long id;
	private LutCountries lutCountries;
	private RegReportReq regReportReq;
	private Integer countryid;
	private Integer reqid;

	public LnkWeeklyCountry() {
	}

	public LnkWeeklyCountry(Long id) {
		this.id = id;
	}

	public LnkWeeklyCountry(Long id, LutCountries lutCountries, RegReportReq regReportReq) {
		this.id = id;
		this.lutCountries = lutCountries;
		this.regReportReq = regReportReq;
	}

	@Id
	@SequenceGenerator(name="REG_REQ_REPORT_SEQ", sequenceName="REG_REQ_REPORT_SEQ", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="REG_REQ_REPORT_SEQ")
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "COUTRYID")	
	public Integer getCountryid() {
		return countryid;
	}

	public void setCountryid(Integer countryid) {
		this.countryid = countryid;
	}

	@Column(name = "REQID")
	public Integer getReqid() {
		return reqid;
	}

	public void setReqid(Integer reqid) {
		this.reqid = reqid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COUTRYID",nullable=false,insertable=false,updatable=false)
	public LutCountries getLutCountries() {
		return this.lutCountries;
	}

	public void setLutCountries(LutCountries lutCountries) {
		this.lutCountries = lutCountries;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REQID",nullable=false,insertable=false,updatable=false)
	public RegReportReq getRegReportReq() {
		return this.regReportReq;
	}

	public void setRegReportReq(RegReportReq regReportReq) {
		this.regReportReq = regReportReq;
	}

}
