package com.peace.users.model.mram;
// Generated Nov 17, 2015 5:32:33 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * LutAppstatus generated by hbm2java
 */
@Entity
@Table(name = "LUT_APPSTATUS")
public class LutAppstatus implements java.io.Serializable {

	private Long id;
	private String statusNameMon;
	private String statusNameEng;
	private Set<RegWeeklyMontly> regWeeklyMontlies = new HashSet<RegWeeklyMontly>(0);
	private Set<LnkAppstepAppstatus> lnkAppstepAppstatuses = new HashSet<LnkAppstepAppstatus>(0);
	private Set<SubReportRegistration> subReportRegistrations = new HashSet<SubReportRegistration>(0);

	public LutAppstatus() {
	}

	public LutAppstatus(Long id, String statusNameMon, String statusNameEng) {
		this.id = id;
		this.statusNameMon = statusNameMon;
		this.statusNameEng = statusNameEng;
	}

	public LutAppstatus(Long id, String statusNameMon, String statusNameEng,
			Set<RegWeeklyMontly> regWeeklyMontlies, Set<LnkAppstepAppstatus> lnkAppstepAppstatuses,
			Set<SubReportRegistration> subReportRegistrations) {
		this.id = id;
		this.statusNameMon = statusNameMon;
		this.statusNameEng = statusNameEng;
		this.regWeeklyMontlies = regWeeklyMontlies;
		this.lnkAppstepAppstatuses = lnkAppstepAppstatuses;
		this.subReportRegistrations = subReportRegistrations;
	}

	@Id
	@SequenceGenerator(name="LUT_APPSTATUS_SEQ", sequenceName="LUT_APPSTATUS_SEQ", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="LUT_APPSTATUS_SEQ")
	@Column(name = "StatusID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	

	@Column(name = "StatusNameMon", nullable = false, length = 100)
	public String getStatusNameMon() {
		return this.statusNameMon;
	}

	public void setStatusNameMon(String statusNameMon) {
		this.statusNameMon = statusNameMon;
	}

	@Column(name = "StatusNameEng", nullable = false, length = 100)
	public String getStatusNameEng() {
		return this.statusNameEng;
	}

	public void setStatusNameEng(String statusNameEng) {
		this.statusNameEng = statusNameEng;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lutAppstatus")
	@JsonBackReference
	public Set<RegWeeklyMontly> getRegWeeklyMontlies() {
		return this.regWeeklyMontlies;
	}

	public void setRegWeeklyMontlies(Set<RegWeeklyMontly> regWeeklyMontlies) {
		this.regWeeklyMontlies = regWeeklyMontlies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lutAppstatus")
	@JsonBackReference
	public Set<LnkAppstepAppstatus> getLnkAppstepAppstatuses() {
		return this.lnkAppstepAppstatuses;
	}

	public void setLnkAppstepAppstatuses(Set<LnkAppstepAppstatus> lnkAppstepAppstatuses) {
		this.lnkAppstepAppstatuses = lnkAppstepAppstatuses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lutAppstatus")
	@JsonBackReference
	public Set<SubReportRegistration> getSubReportRegistrations() {
		return this.subReportRegistrations;
	}

	public void setSubReportRegistrations(Set<SubReportRegistration> subReportRegistrations) {
		this.subReportRegistrations = subReportRegistrations;
	}

}
