package com.peace.users.model.mram;
// Generated Feb 20, 2016 4:10:23 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LutAdminunit generated by hbm2java
 */
@Entity
@Table(name = "LUT_ADMINUNIT")
public class LutAdminunit implements java.io.Serializable {

	private Long sid;
	private LutAdminunit lutAdminunit;
	private Long id;
	private Long parentid;
	private String name;
	private String nameL1;
	private Set<LutAdminunit> lutAdminunits = new HashSet<LutAdminunit>(0);

	public LutAdminunit() {
	}

	public LutAdminunit(Long sid, Long id) {
		this.sid = sid;
		this.id = id;
	}

	public LutAdminunit(Long sid, LutAdminunit lutAdminunit, Long id, String name, String nameL1,
			Set<LutAdminunit> lutAdminunits) {
		this.sid = sid;
		this.lutAdminunit = lutAdminunit;
		this.id = id;
		this.name = name;
		this.nameL1 = nameL1;
		this.lutAdminunits = lutAdminunits;
	}

	@Id

	@Column(name = "SID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getSid() {
		return this.sid;
	}

	public void setSid(Long sid) {
		this.sid = sid;
	}

	
	
	@Column(name = "PARENT_ID")
	public Long getParentid() {
		return parentid;
	}

	public void setParentid(Long parentid) {
		this.parentid = parentid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PARENT_ID",insertable=false,nullable=false,updatable=false)
	public LutAdminunit getLutAdminunit() {
		return this.lutAdminunit;
	}

	public void setLutAdminunit(LutAdminunit lutAdminunit) {
		this.lutAdminunit = lutAdminunit;
	}

	
	@Column(name = "ID", nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "NAME_L1")
	public String getNameL1() {
		return this.nameL1;
	}

	public void setNameL1(String nameL1) {
		this.nameL1 = nameL1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lutAdminunit")
	public Set<LutAdminunit> getLutAdminunits() {
		return this.lutAdminunits;
	}

	public void setLutAdminunits(Set<LutAdminunit> lutAdminunits) {
		this.lutAdminunits = lutAdminunits;
	}

}
