package com.peace.users.model.mram;
// Generated Nov 17, 2015 5:32:33 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * LutAppsteps generated by hbm2java
 */
@Entity
@Table(name = "LUT_APPSTEPS")
public class LutAppsteps implements java.io.Serializable {

	private Long id;
	private String stepsNameMon;
	private String stepsNameEng;
	private Long divisionId;
	private Set<SubApprovals> subApprovalses = new HashSet<SubApprovals>(0);
	private Set<LnkAppstepAppstatus> lnkAppstepAppstatuses = new HashSet<LnkAppstepAppstatus>(0);

	public LutAppsteps() {
	}

	public LutAppsteps(Long id, String stepsNameMon, String stepsNameEng) {
		this.id = id;
		this.stepsNameMon = stepsNameMon;
		this.stepsNameEng = stepsNameEng;
	}

	public LutAppsteps(Long id, String stepsNameMon, String stepsNameEng, Long divisionId,
			Set<SubApprovals> subApprovalses, Set<LnkAppstepAppstatus> lnkAppstepAppstatuses) {
		this.id = id;
		this.stepsNameMon = stepsNameMon;
		this.stepsNameEng = stepsNameEng;
		this.divisionId = divisionId;
		this.subApprovalses = subApprovalses;
		this.lnkAppstepAppstatuses = lnkAppstepAppstatuses;
	}

	@Id
	@SequenceGenerator(name="LUT_APPSTEPS_SEQ", sequenceName="LUT_APPSTEPS_SEQ", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="LUT_APPSTEPS_SEQ")
	@Column(name = "StepsID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
		
	@Column(name = "StepsNameMon", nullable = false, length = 70)
	public String getStepsNameMon() {
		return this.stepsNameMon;
	}

	public void setStepsNameMon(String stepsNameMon) {
		this.stepsNameMon = stepsNameMon;
	}

	@Column(name = "StepsNameEng", nullable = false, length = 70)
	public String getStepsNameEng() {
		return this.stepsNameEng;
	}

	public void setStepsNameEng(String stepsNameEng) {
		this.stepsNameEng = stepsNameEng;
	}

	@Column(name = "DivisionID", precision = 22, scale = 0)
	public Long getDivisionId() {
		return this.divisionId;
	}

	public void setDivisionId(Long divisionId) {
		this.divisionId = divisionId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lutAppsteps")
	@JsonBackReference
	public Set<SubApprovals> getSubApprovalses() {
		return this.subApprovalses;
	}

	public void setSubApprovalses(Set<SubApprovals> subApprovalses) {
		this.subApprovalses = subApprovalses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lutAppsteps")
	@JsonBackReference
	public Set<LnkAppstepAppstatus> getLnkAppstepAppstatuses() {
		return this.lnkAppstepAppstatuses;
	}

	public void setLnkAppstepAppstatuses(Set<LnkAppstepAppstatus> lnkAppstepAppstatuses) {
		this.lnkAppstepAppstatuses = lnkAppstepAppstatuses;
	}

}
