package com.peace.users.model.mram;
// Generated Mar 22, 2016 11:48:00 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LutConcentration generated by hbm2java
 */
@Entity
@Table(name = "LUT_CONCENTRATION")
public class LutConcentration implements java.io.Serializable {

	private long id;
	private String namemon;
	private String nameeng;
	private int isconcentrate;

	public LutConcentration() {
	}

	public LutConcentration(long id) {
		this.id = id;
	}

	public LutConcentration(long id, String namemon, String nameeng) {
		this.id = id;
		this.namemon = namemon;
		this.nameeng = nameeng;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
		
	@Column(name = "ISCONCENTRATE")
	public int getIsconcentrate() {
		return isconcentrate;
	}

	public void setIsconcentrate(int isconcentrate) {
		this.isconcentrate = isconcentrate;
	}

	@Column(name = "NAMEMON")
	public String getNamemon() {
		return this.namemon;
	}

	public void setNamemon(String namemon) {
		this.namemon = namemon;
	}

	@Column(name = "NAMEENG")
	public String getNameeng() {
		return this.nameeng;
	}

	public void setNameeng(String nameeng) {
		this.nameeng = nameeng;
	}

}
