package com.peace.users.model.mram;
// Generated Nov 17, 2015 5:32:33 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LutDecisions generated by hbm2java
 */
@Entity
@Table(name = "LUT_DECISIONS")
public class LutDecisions implements java.io.Serializable {

	private Long decisionId;
	private String decisionNameMon;
	private String decisionNameEng;
	private Set<SubApprovals> subApprovalses = new HashSet<SubApprovals>(0);
	private Set<LnkComment> lnkComment = new HashSet<LnkComment>(0);
	
	private Set<LnkPlanTransition> lnkPlanTransition = new HashSet<LnkPlanTransition>(0);
	private Set<LnkCommentMain> lnkCommentMain = new HashSet<LnkCommentMain>(0);

	public LutDecisions() {
	}

	public LutDecisions(Long decisionId, String decisionNameMon, String decisionNameEng) {
		this.decisionId = decisionId;
		this.decisionNameMon = decisionNameMon;
		this.decisionNameEng = decisionNameEng;
	}

	public LutDecisions(Long decisionId, String decisionNameMon, String decisionNameEng,
			Set<SubApprovals> subApprovalses) {
		this.decisionId = decisionId;
		this.decisionNameMon = decisionNameMon;
		this.decisionNameEng = decisionNameEng;
		this.subApprovalses = subApprovalses;
	}

	@Id

	@Column(name = "DecisionID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getDecisionId() {
		return this.decisionId;
	}

	public void setDecisionId(Long decisionId) {
		this.decisionId = decisionId;
	}

	@Column(name = "DecisionNameMon", nullable = false, length = 100)
	public String getDecisionNameMon() {
		return this.decisionNameMon;
	}

	public void setDecisionNameMon(String decisionNameMon) {
		this.decisionNameMon = decisionNameMon;
	}

	@Column(name = "DecisionNameEng", nullable = false, length = 100)
	public String getDecisionNameEng() {
		return this.decisionNameEng;
	}

	public void setDecisionNameEng(String decisionNameEng) {
		this.decisionNameEng = decisionNameEng;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lutDecisions")
	public Set<SubApprovals> getSubApprovalses() {
		return this.subApprovalses;
	}

	public void setSubApprovalses(Set<SubApprovals> subApprovalses) {
		this.subApprovalses = subApprovalses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lutDecisions")
	public Set<LnkComment> getLnkComment() {
		return lnkComment;
	}

	public void setLnkComment(Set<LnkComment> lnkComment) {
		this.lnkComment = lnkComment;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lutDecisions")
	public Set<LnkPlanTransition> getLnkPlanTransition() {
		return lnkPlanTransition;
	}

	public void setLnkPlanTransition(Set<LnkPlanTransition> lnkPlanTransition) {
		this.lnkPlanTransition = lnkPlanTransition;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lutDecisions")
	public Set<LnkCommentMain> getLnkCommentMain() {
		return lnkCommentMain;
	}

	public void setLnkCommentMain(Set<LnkCommentMain> lnkCommentMain) {
		this.lnkCommentMain = lnkCommentMain;
	}

	

}
