package com.peace.users.model.mram;
// Generated Nov 25, 2015 5:34:04 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LutFormindicators generated by hbm2java
 */
@Entity
@Table(name = "LUT_FORMINDICATORS")
public class LutFormindicators implements java.io.Serializable {

	private Long id;
	private LutForms lutForms;
	private Long indicatorid;
	private Long formid;
	private Long divisionid;
	private String indicatornamemon;
	private String indicatornameeng;
	private Long measID;
	public LutFormindicators() {
	}

	public LutFormindicators(Long id, String indicatornamemon) {
		this.id = id;
		this.indicatornamemon = indicatornamemon;
	}

	public LutFormindicators(Long id, LutForms lutForms, Long indicatorid, String indicatornamemon,
			String indicatornameeng) {
		this.id = id;
		this.lutForms = lutForms;
		this.indicatorid = indicatorid;
		this.indicatornamemon = indicatornamemon;
		this.indicatornameeng = indicatornameeng;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	@Column(name = "FORMID")
	public Long getFormid() {
		return formid;
	}

	public void setFormid(Long formid) {
		this.formid = formid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FORMID",nullable=false,insertable=false,updatable=false)
	public LutForms getLutForms() {
		return this.lutForms;
	}

	public void setLutForms(LutForms lutForms) {
		this.lutForms = lutForms;
	}

	
	@Column(name = "DIVISIONID")
	public Long getDivisionid() {
		return divisionid;
	}

	public void setDivisionid(Long divisionid) {
		this.divisionid = divisionid;
	}

	@Column(name = "INDICATORID", precision = 22, scale = 0)
	public Long getIndicatorid() {
		return this.indicatorid;
	}

	public void setIndicatorid(Long indicatorid) {
		this.indicatorid = indicatorid;
	}

	@Column(name = "INDICATORNAMEMON", nullable = false, length = 100)
	public String getIndicatornamemon() {
		return this.indicatornamemon;
	}

	public void setIndicatornamemon(String indicatornamemon) {
		this.indicatornamemon = indicatornamemon;
	}

	@Column(name = "INDICATORNAMEENG", length = 100)
	public String getIndicatornameeng() {
		return this.indicatornameeng;
	}

	public void setIndicatornameeng(String indicatornameeng) {
		this.indicatornameeng = indicatornameeng;
	}

	@Column(name = "MEASID", length = 100)
	public Long getMeasID() {
		return measID;
	}

	public void setMeasID(Long measID) {
		this.measID = measID;
	}
	
}
