package com.peace.users.model.mram;
// Generated Nov 17, 2015 5:32:33 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * LutFiletype generated by hbm2java
 */
@Entity
@Table(name = "LUT_FILETYPE")
public class LutFiletype implements java.io.Serializable {

	private Long id;
	private String fileTypeName;
	private Long fileMaxSize;
	private Set<LutForms> lutFormses = new HashSet<LutForms>(0);

	public LutFiletype() {
	}

	public LutFiletype(Long id, String fileTypeName, Long fileMaxSize) {
		this.id = id;
		this.fileTypeName = fileTypeName;
		this.fileMaxSize = fileMaxSize;
	}

	public LutFiletype(Long id, String fileTypeName, Long fileMaxSize, Set<LutForms> lutFormses) {
		this.id = id;
		this.fileTypeName = fileTypeName;
		this.fileMaxSize = fileMaxSize;
		this.lutFormses = lutFormses;
	}

	@Id
	@SequenceGenerator(name="LUT_FILETYPE_SEQ", sequenceName="LUT_FILETYPE_SEQ", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="LUT_FILETYPE_SEQ")
	@Column(name = "FileTypeID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	

	@Column(name = "FileTypeName", nullable = false, length = 70)
	public String getFileTypeName() {
		return this.fileTypeName;
	}

	

	public void setFileTypeName(String fileTypeName) {
		this.fileTypeName = fileTypeName;
	}

	@Column(name = "FileMaxSize", nullable = false, precision = 22, scale = 0)
	public Long getFileMaxSize() {
		return this.fileMaxSize;
	}

	public void setFileMaxSize(Long fileMaxSize) {
		this.fileMaxSize = fileMaxSize;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lutFiletype")
	@JsonBackReference
	public Set<LutForms> getLutFormses() {
		return this.lutFormses;
	}

	public void setLutFormses(Set<LutForms> lutFormses) {
		this.lutFormses = lutFormses;
	}

}
