package com.peace.users.model.mram;
// Generated Dec 11, 2015 4:54:27 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * LutFormNotes generated by hbm2java
 */
@Entity
@Table(name = "LUT_FORM_NOTES")
public class LutFormNotes implements java.io.Serializable {
	private static final long serialVersionUID = 1L;


	private long id;
	private String note;
	private Long reporttype;
	private Long lictype;
	private Integer inptype;
	private Integer divisionid;
	private Integer transid;
	private Integer onoffid;
	private Integer isfile;
	private String url;
	private String notecontent;
	private Integer isform;
	private Integer fsize;
	private Integer isapproval;
	
	private Integer isexplosion;
	private Integer isconcentrate;
	private Integer ismatter;
	private Integer iscommon;
	
	
	private Integer lplan;
	private Integer	lreport;
	
	private Integer iskomiss;
	private Integer isbudget;
	
	private Integer isxreport;
	private Integer isrequired;
	private Integer mintypeid;
	
	private List<LnkPlanNotes> lnkPlanNoteses = new ArrayList<LnkPlanNotes>();
	private List<LnkPlanTransition> lnkPlanTransitions = new ArrayList<LnkPlanTransition>();
	private List<LnkPlanAttachedFiles> lnkPlanAttachedFileses =  new ArrayList<LnkPlanAttachedFiles>();
	private List<LnkComment> LnkCommentes =  new ArrayList<LnkComment>();
	
	public LutFormNotes() {
	}

	public LutFormNotes(long id) {
		this.id = id;
	}

	public LutFormNotes(long id, String note, Long reporttype, Long lictype, List<LnkPlanNotes> lnkPlanNoteses) {
		this.id = id;
		this.note = note;
		this.reporttype = reporttype;
		this.lictype = lictype;
		this.lnkPlanNoteses = lnkPlanNoteses;
	}


	@Id
	@SequenceGenerator(name="LUT_FORM_NOTES_SEQ", sequenceName="LUT_FORM_NOTES_SEQ",allocationSize=1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="LUT_FORM_NOTES_SEQ")
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "NOTE")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "REPORTTYPE", precision = 10, scale = 0)
	public Long getReporttype() {
		return this.reporttype;
	}

	public void setReporttype(Long reporttype) {
		this.reporttype = reporttype;
	}

	@Column(name = "LICTYPE", precision = 10, scale = 0)
	public Long getLictype() {
		return this.lictype;
	}

	public void setLictype(Long lictype) {
		this.lictype = lictype;
	}

	
	@Column(name = "TRANSID", precision = 10, scale = 0)
	public Integer getTransid() {
		return transid;
	}

	public void setTransid(Integer transid) {
		this.transid = transid;
	}

	@Column(name = "ONOFFID", precision = 10, scale = 0)
	public Integer getOnoffid() {
		return onoffid;
	}

	public void setOnoffid(Integer onoffid) {
		this.onoffid = onoffid;
	}

	@Column(name = "DIVISIONID", precision = 10, scale = 0)
	public Integer getDivisionid() {
		return divisionid;
	}

	public void setDivisionid(Integer divisionid) {
		this.divisionid = divisionid;
	}

	@Column(name = "INPTYPE", precision = 10, scale = 0)
	public Integer getInptype() {
		return inptype;
	}

	public void setInptype(Integer inptype) {
		this.inptype = inptype;
	}
	
	@Column(name = "ISREQUIRED")
	public Integer getIsrequired() {
		return isrequired;
	}

	public void setIsrequired(Integer isrequired) {
		this.isrequired = isrequired;
	}
	
	@Column(name = "MINTYPEID")
	public Integer getMintypeid() {
		return mintypeid;
	}

	public void setMintypeid(Integer mintypeid) {
		this.mintypeid = mintypeid;
	}

	@Column(name = "ISAPPROVAL")
	public Integer getIsapproval() {
		return isapproval;
	}

	public void setIsapproval(Integer isapproval) {
		this.isapproval = isapproval;
	}

	@Column(name = "URL")
	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}
	
	@Column(name = "ISCOMMON")
	public Integer getIscommon() {
		return iscommon;
	}

	public void setIscommon(Integer iscommon) {
		this.iscommon = iscommon;
	}

	@Column(name = "ISFORM")
	public Integer getIsform() {
		return isform;
	}

	public void setIsform(Integer isform) {
		this.isform = isform;
	}

	@Column(name = "FSIZE")
	public Integer getFsize() {
		return fsize;
	}

	public void setFsize(Integer fsize) {
		this.fsize = fsize;
	}
	
	@Column(name = "ISEXPLOSION")
	public Integer getIsexplosion() {
		return isexplosion;
	}

	public void setIsexplosion(Integer isexplosion) {
		this.isexplosion = isexplosion;
	}

	@Column(name = "ISCONCENTRATE")
	public Integer getIsconcentrate() {
		return isconcentrate;
	}

	public void setIsconcentrate(Integer isconcentrate) {
		this.isconcentrate = isconcentrate;
	}

	@Column(name = "ISMATTER")
	public Integer getIsmatter() {
		return ismatter;
	}

	public void setIsmatter(Integer ismatter) {
		this.ismatter = ismatter;
	}

	@Column(name = "NOTECONTENT")
	public String getNotecontent() {
		return notecontent;
	}

	public void setNotecontent(String notecontent) {
		this.notecontent = notecontent;
	}

	@Column(name = "ISFILE")
	public Integer getIsfile() {
		return isfile;
	}

	public void setIsfile(Integer isfile) {
		this.isfile = isfile;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lutFormNotes")
	@JsonBackReference
	public List<LnkPlanNotes> getLnkPlanNoteses() {
		return this.lnkPlanNoteses;
	}

	public void setLnkPlanNoteses(List<LnkPlanNotes> lnkPlanNoteses) {
		this.lnkPlanNoteses = lnkPlanNoteses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lutFormNotes")
	@JsonBackReference
	public List<LnkPlanAttachedFiles> getLnkPlanAttachedFileses() {
		return lnkPlanAttachedFileses;
	}

	public void setLnkPlanAttachedFileses(List<LnkPlanAttachedFiles> lnkPlanAttachedFileses) {
		this.lnkPlanAttachedFileses = lnkPlanAttachedFileses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lutFormNotes")
	@JsonBackReference
	public List<LnkComment> getLnkCommentes() {
		return LnkCommentes;
	}

	public void setLnkCommentes(List<LnkComment> lnkCommentes) {
		LnkCommentes = lnkCommentes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lutFormNotes")
	@JsonBackReference
	public List<LnkPlanTransition> getLnkPlanTransitions() {
		return lnkPlanTransitions;
	}

	public void setLnkPlanTransitions(List<LnkPlanTransition> lnkPlanTransitions) {
		this.lnkPlanTransitions = lnkPlanTransitions;
	}

	public Integer getIskomiss() {
		return iskomiss;
	}

	public void setIskomiss(Integer iskomiss) {
		this.iskomiss = iskomiss;
	}

	public Integer getIsbudget() {
		return isbudget;
	}

	public void setIsbudget(Integer isbudget) {
		this.isbudget = isbudget;
	}

	public Integer getLplan() {
		return lplan;
	}

	public void setLplan(Integer lplan) {
		this.lplan = lplan;
	}

	public Integer getLreport() {
		return lreport;
	}

	public void setLreport(Integer lreport) {
		this.lreport = lreport;
	}

	public Integer getIsxreport() {
		return isxreport;
	}

	public void setIsxreport(Integer isxreport) {
		this.isxreport = isxreport;
	}
		
}
