package com.peace.users.model.mram;
// Generated Nov 17, 2015 5:32:33 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * LutLicstatus generated by hbm2java
 */
@Entity
@Table(name = "LUT_LICSTATUS")
public class LutLicstatus implements java.io.Serializable {

	private Long id;
	private String licStatusNameMon;
	private String licStatusNameEng;
	private Set<SubLicenses> subLicenseses = new HashSet<SubLicenses>(0);

	public LutLicstatus() {
	}

	public LutLicstatus(Long id, String licStatusNameMon, String licStatusNameEng) {
		this.id = id;
		this.licStatusNameMon = licStatusNameMon;
		this.licStatusNameEng = licStatusNameEng;
	}

	public LutLicstatus(Long id, String licStatusNameMon, String licStatusNameEng,
			Set<SubLicenses> subLicenseses) {
		this.id = id;
		this.licStatusNameMon = licStatusNameMon;
		this.licStatusNameEng = licStatusNameEng;
		this.subLicenseses = subLicenseses;
	}

	@Id
	@SequenceGenerator(name="LUT_LICSTATUS_SEQ", sequenceName="LUT_LICSTATUS_SEQ", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="LUT_LICSTATUS_SEQ")
	@Column(name = "LicStatusID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	

	@Column(name = "LicStatusNameMon", nullable = false, length = 70)
	public String getLicStatusNameMon() {
		return this.licStatusNameMon;
	}



	public void setLicStatusNameMon(String licStatusNameMon) {
		this.licStatusNameMon = licStatusNameMon;
	}

	@Column(name = "LicStatusNameEng", nullable = false, length = 70)
	public String getLicStatusNameEng() {
		return this.licStatusNameEng;
	}

	public void setLicStatusNameEng(String licStatusNameEng) {
		this.licStatusNameEng = licStatusNameEng;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lutLicstatus")
	public Set<SubLicenses> getSubLicenseses() {
		return this.subLicenseses;
	}

	public void setSubLicenseses(Set<SubLicenses> subLicenseses) {
		this.subLicenseses = subLicenseses;
	}

}
