package com.peace.users.model.mram;
// Generated Nov 25, 2015 5:34:04 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LutLptype generated by hbm2java
 */
@Entity
@Table(name = "LUT_LPTYPE")
public class LutLptype implements java.io.Serializable {

	private Long id;
	private String lptype;
	private String lptypedecsmon;
	private String lptypedecseng;
	private String lptypeeng;

	private Set<SubLegalpersons> subLegalpersonses = new HashSet<SubLegalpersons>(0);
	
	public LutLptype() {
	}

	public LutLptype(Long id) {
		this.id = id;
	}

	public LutLptype(Long id, String lptype, String lptypedecsmon, String lptypedecseng, String lptypeeng) {
		this.id = id;
		this.lptype = lptype;
		this.lptypedecsmon = lptypedecsmon;
		this.lptypedecseng = lptypedecseng;
		this.lptypeeng = lptypeeng;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "LPTYPE", length = 200)
	public String getLptype() {
		return this.lptype;
	}

	public void setLptype(String lptype) {
		this.lptype = lptype;
	}

	@Column(name = "LPTYPEDECSMON")
	public String getLptypedecsmon() {
		return this.lptypedecsmon;
	}

	public void setLptypedecsmon(String lptypedecsmon) {
		this.lptypedecsmon = lptypedecsmon;
	}

	@Column(name = "LPTYPEDECSENG")
	public String getLptypedecseng() {
		return this.lptypedecseng;
	}

	public void setLptypedecseng(String lptypedecseng) {
		this.lptypedecseng = lptypedecseng;
	}

	@Column(name = "LPTYPEENG")
	public String getLptypeeng() {
		return this.lptypeeng;
	}

	public void setLptypeeng(String lptypeeng) {
		this.lptypeeng = lptypeeng;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lutLptype")
	public Set<SubLegalpersons> getSubLegalpersonses() {
		return this.subLegalpersonses;
	}

	public void setSubLegalpersonses(Set<SubLegalpersons> subLegalpersonses) {
		this.subLegalpersonses = subLegalpersonses;
	}
}
