package com.peace.users.model.mram;
// Generated Nov 17, 2015 5:32:33 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * LutLictype generated by hbm2java
 */
@Entity
@Table(name = "LUT_LICTYPE")
public class LutLictype implements java.io.Serializable {

	private Long id;
	private String licTypeNameMon;
	private String licTypeNameEng;
	private Set<SubLicenses> subLicenseses = new HashSet<SubLicenses>(0);

	public LutLictype() {
	}

	public LutLictype(Long id, String licTypeNameMon, String licTypeNameEng) {
		this.id = id;
		this.licTypeNameMon = licTypeNameMon;
		this.licTypeNameEng = licTypeNameEng;
	}

	public LutLictype(Long id, String licTypeNameMon, String licTypeNameEng,
			Set<SubLicenses> subLicenseses) {
		this.id = id;
		this.licTypeNameMon = licTypeNameMon;
		this.licTypeNameEng = licTypeNameEng;
		this.subLicenseses = subLicenseses;
	}

	@Id
	@SequenceGenerator(name="LUT_LICTYPE_SEQ", sequenceName="LUT_LICTYPE_SEQ", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="LUT_LICTYPE_SEQ")
	@Column(name = "LicTypeID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	

	@Column(name = "LicTypeNameMon", nullable = false, length = 50)
	public String getLicTypeNameMon() {
		return this.licTypeNameMon;
	}



	public void setLicTypeNameMon(String licTypeNameMon) {
		this.licTypeNameMon = licTypeNameMon;
	}

	@Column(name = "LicTypeNameEng", nullable = false, length = 50)
	public String getLicTypeNameEng() {
		return this.licTypeNameEng;
	}

	public void setLicTypeNameEng(String licTypeNameEng) {
		this.licTypeNameEng = licTypeNameEng;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lutLictype")
	public Set<SubLicenses> getSubLicenseses() {
		return this.subLicenseses;
	}

	public void setSubLicenseses(Set<SubLicenses> subLicenseses) {
		this.subLicenseses = subLicenseses;
	}

}
