package com.peace.users.model.mram;
// Generated Feb 3, 2016 7:11:36 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * LutMeasurements generated by hbm2java
 */
@Entity
@Table(name = "LUT_MEASUREMENTS")
public class LutMeasurements implements java.io.Serializable {

	private Long id;
	private String measnamemon;
	private String measnameeng;
	private Set<LutMinerals> lutMineralses = new HashSet<LutMinerals>(0);
	private Set<LutSubProduct> lutSubProducts = new HashSet<LutSubProduct>(0);
	private Set<LutDeposit> lutDeposits = new HashSet<LutDeposit>(0);
	private Set<LutProducts> lutProductses = new HashSet<LutProducts>(0);

	public LutMeasurements() {
	}

	public LutMeasurements(Long id, String measnamemon, String measnameeng) {
		this.id = id;
		this.measnamemon = measnamemon;
		this.measnameeng = measnameeng;
	}

	public LutMeasurements(Long id, String measnamemon, String measnameeng, Set<LutMinerals> lutMineralses,
			Set<LutSubProduct> lutSubProducts, Set<LutDeposit> lutDeposits, 
			Set<LutProducts> lutProductses) {
		this.id = id;
		this.measnamemon = measnamemon;
		this.measnameeng = measnameeng;
		this.lutMineralses = lutMineralses;
		this.lutSubProducts = lutSubProducts;
		this.lutDeposits = lutDeposits;
		this.lutProductses = lutProductses;
	}


	@Id
	@SequenceGenerator(name="LUT_MEASUREMENTS_SEQ", sequenceName="LUT_MEASUREMENTS_SEQ", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="LUT_MEASUREMENTS_SEQ")
	@Column(name = "MEASID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}	
	
	
	@Column(name = "MEASNAMEMON", nullable = false, length = 70)
	public String getMeasnamemon() {
		return this.measnamemon;
	}

	public void setMeasnamemon(String measnamemon) {
		this.measnamemon = measnamemon;
	}

	@Column(name = "MEASNAMEENG", nullable = false, length = 70)
	public String getMeasnameeng() {
		return this.measnameeng;
	}

	public void setMeasnameeng(String measnameeng) {
		this.measnameeng = measnameeng;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lutMeasurements")
	@JsonBackReference
	public Set<LutMinerals> getLutMineralses() {
		return this.lutMineralses;
	}

	public void setLutMineralses(Set<LutMinerals> lutMineralses) {
		this.lutMineralses = lutMineralses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lutMeasurements")
	@JsonBackReference
	public Set<LutSubProduct> getLutSubProducts() {
		return this.lutSubProducts;
	}

	public void setLutSubProducts(Set<LutSubProduct> lutSubProducts) {
		this.lutSubProducts = lutSubProducts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lutMeasurements")
	@JsonBackReference
	public Set<LutDeposit> getLutDeposits() {
		return this.lutDeposits;
	}

	public void setLutDeposits(Set<LutDeposit> lutDeposits) {
		this.lutDeposits = lutDeposits;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lutMeasurements")
	@JsonBackReference
	public Set<LutProducts> getLutProductses() {
		return this.lutProductses;
	}

	public void setLutProductses(Set<LutProducts> lutProductses) {
		this.lutProductses = lutProductses;
	}

}