package com.peace.users.model.mram;
// Generated Feb 4, 2016 2:31:00 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LutMinGroup generated by hbm2java
 */
@Entity
@Table(name = "LUT_MIN_GROUP")
public class LutMinGroup implements java.io.Serializable {

	private Long id;
	private String groupname;
	private int isactive;

	public LutMinGroup() {
	}



	@Id

	@Column(name = "GROUPID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	
	
	
	@Column(name = "ISACTIVE")
	public int getIsactive() {
		return isactive;
	}



	public void setIsactive(int isactive) {
		this.isactive = isactive;
	}



	@Column(name = "GROUPNAME")
	public String getGroupname() {
		return this.groupname;
	}
	public void setGroupname(String groupname) {
		this.groupname = groupname;
	}

}
