package com.peace.users.model.mram;
// Generated Feb 4, 2016 2:31:00 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * LutMinerals generated by hbm2java
 */
@Entity
@Table(name = "LUT_MINERALS")
public class LutMinerals implements java.io.Serializable {

	private Long id;
	private LutMeasurements lutMeasurements;
	private String mineralnamemon;
	private String mineralnameeng;
	private Integer mineralgroupid;
	private Set<LutDeposit> lutDeposits = new HashSet<LutDeposit>(0);

	public LutMinerals() {
	}

	public LutMinerals(Long id) {
		this.id = id;
	}

	public LutMinerals(Long id, LutMeasurements lutMeasurements, String mineralnamemon,
			String mineralnameeng, Integer mineralgroupid, Set<LutDeposit> lutDeposits) {
		this.id = id;
		this.lutMeasurements = lutMeasurements;
		this.mineralnamemon = mineralnamemon;
		this.mineralnameeng = mineralnameeng;
		this.mineralgroupid = mineralgroupid;
		this.lutDeposits = lutDeposits;
	}

	@Id

	@Column(name = "MINERALID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MEASID")
	@JsonBackReference
	public LutMeasurements getLutMeasurements() {
		return this.lutMeasurements;
	}



	public void setLutMeasurements(LutMeasurements lutMeasurements) {
		this.lutMeasurements = lutMeasurements;
	}

	@Column(name = "MINERALNAMEMON", length = 100)
	public String getMineralnamemon() {
		return this.mineralnamemon;
	}

	public void setMineralnamemon(String mineralnamemon) {
		this.mineralnamemon = mineralnamemon;
	}

	@Column(name = "MINERALNAMEENG", length = 100)
	public String getMineralnameeng() {
		return this.mineralnameeng;
	}

	public void setMineralnameeng(String mineralnameeng) {
		this.mineralnameeng = mineralnameeng;
	}

	@Column(name = "MINERALGROUPID", precision = 2, scale = 0)
	public Integer getMineralgroupid() {
		return this.mineralgroupid;
	}

	public void setMineralgroupid(Integer mineralgroupid) {
		this.mineralgroupid = mineralgroupid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lutMinerals")
	@JsonBackReference
	public Set<LutDeposit> getLutDeposits() {
		return this.lutDeposits;
	}

	public void setLutDeposits(Set<LutDeposit> lutDeposits) {
		this.lutDeposits = lutDeposits;
	}

}
