package com.peace.users.model.mram;
// Generated Nov 17, 2015 5:32:33 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.peace.users.model.Pmenu;

/**
 * LutMenu generated by hbm2java
 */
@Entity
@Table(name = "LUT_MENU")
public class LutMenu implements java.io.Serializable {

	private Long id;
	private String namemn;
	private String nameen;
	private Integer parentid;
	private Integer orderid;
	private Integer isactive;
	private String stateurl;
	private String icon;
	private List<LnkMenuRole> lnkMenuRoles = new ArrayList<LnkMenuRole>();
	private LutMenu parent;
	private List<LutMenu> childs = new ArrayList<LutMenu>();
	public LutMenu() {
	}

	public LutMenu(Long id) {
		this.id = id;
	}

	public LutMenu(Long id, String namemn, String nameen, Integer parentid, Integer orderid,
			Integer isactive, String stateurl, String icon, List<LnkMenuRole> lnkMenuRoles) {
		this.id = id;
		this.namemn = namemn;
		this.nameen = nameen;
		this.parentid = parentid;
		this.orderid = orderid;
		this.isactive = isactive;
		this.stateurl = stateurl;
		this.icon = icon;
		this.lnkMenuRoles = lnkMenuRoles;
	}

	@Id
	@SequenceGenerator(name="LUT_MENU_SEQ", sequenceName="LUT_MENU_SEQ")
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="LUT_MENU_SEQ")
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "NAMEMN")
	public String getNamemn() {
		return this.namemn;
	}

	public void setNamemn(String namemn) {
		this.namemn = namemn;
	}

	@Column(name = "NAMEEN")
	public String getNameen() {
		return this.nameen;
	}

	public void setNameen(String nameen) {
		this.nameen = nameen;
	}

	@Column(name = "PARENTID", precision = 22, scale = 0)
	public Integer getParentid() {
		return this.parentid;
	}

	public void setParentid(Integer parentid) {
		this.parentid = parentid;
	}

	@Column(name = "ORDERID", precision = 22, scale = 0)
	public Integer getOrderid() {
		return this.orderid;
	}

	public void setOrderid(Integer orderid) {
		this.orderid = orderid;
	}

	@Column(name = "ISACTIVE", precision = 22, scale = 0)
	public Integer getIsactive() {
		return this.isactive;
	}

	public void setIsactive(Integer isactive) {
		this.isactive = isactive;
	}

	@Column(name = "STATEURL")
	public String getStateurl() {
		return this.stateurl;
	}

	public void setStateurl(String stateurl) {
		this.stateurl = stateurl;
	}

	@Column(name = "ICON")
	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lutMenu")
	@OrderBy("ID")
	public List<LnkMenuRole> getLnkMenuRoles() {
		return this.lnkMenuRoles;
	}

	public void setLnkMenuRoles(List<LnkMenuRole> lnkMenuRoles) {
		this.lnkMenuRoles = lnkMenuRoles;
	}

	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PARENTID",referencedColumnName="ID",nullable = false,insertable=false,updatable=false)	
	@OrderBy("orderid")
	public LutMenu getParent() {
		return parent;
	}

	public void setParent(LutMenu parent) {
		this.parent = parent;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "parent",cascade=CascadeType.ALL,orphanRemoval=true)	
	@OrderBy("orderid")
	public List<LutMenu> getChilds() {
		return childs;
	}

	public void setChilds(List<LutMenu> childs) {
		this.childs = childs;
	}

}
