package com.peace.users.model.mram;
// Generated Nov 25, 2015 5:34:04 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * LutMineType generated by hbm2java
 */
@Entity
@Table(name = "LUT_MINE_TYPE")
public class LutMineType implements java.io.Serializable {

	private Long id;
	private String mtypeNameMon;
	private String mtypeNameEng;

	public LutMineType() {
	}

	public LutMineType(Long id, String mtypeNameMon, String mtypeNameEng) {
		this.id = id;
		this.mtypeNameMon = mtypeNameMon;
		this.mtypeNameEng = mtypeNameEng;
	}

	@Id
	@SequenceGenerator(name="LUT_APPSTATUS_SEQ", sequenceName="LUT_APPSTATUS_SEQ", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="LUT_APPSTATUS_SEQ")
	@Column(name = "MTYPEID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	
	

	@Column(name = "MTYPENAMEMON", nullable = false, length = 50)
	public String getMtypeNameMon() {
		return this.mtypeNameMon;
	}
	public void setMtypeNameMon(String mtypeNameMon) {
		this.mtypeNameMon = mtypeNameMon;
	}

	@Column(name = "MTYPENAMEENG", nullable = false, length = 50)
	public String getMtypeNameEng() {
		return this.mtypeNameEng;
	}

	public void setMtypeNameEng(String mtypeNameEng) {
		this.mtypeNameEng = mtypeNameEng;
	}

}
