package com.peace.users.model.mram;
// Generated Feb 4, 2016 2:31:00 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * LutProducts generated by hbm2java
 */
@Entity
@Table(name = "LUT_PRODUCTS")
public class LutProducts implements java.io.Serializable {

	private Long productid;
	private LutMeasurements lutMeasurements;
	private LutDeposit lutDeposit;
	private Long depositid;
	private String productnamemon;
	private String productnameeng;
	private Set<LutSubProduct> lutSubProducts = new HashSet<LutSubProduct>(0);
	private Set<LnkWeeklyProduct> lnkWeeklyProducts = new HashSet<LnkWeeklyProduct>(0);

	public LutProducts() {
	}

	public LutProducts(Long productid, String productnamemon, String productnameeng) {
		this.productid = productid;
		this.productnamemon = productnamemon;
		this.productnameeng = productnameeng;
	}

	public LutProducts(Long productid, LutMeasurements lutMeasurements, LutDeposit lutDeposit,
			String productnamemon, String productnameeng,
			Set<LutSubProduct> lutSubProducts) {
		this.productid = productid;
		this.lutMeasurements = lutMeasurements;
		this.lutDeposit = lutDeposit;
		this.productnamemon = productnamemon;
		this.productnameeng = productnameeng;
		this.lutSubProducts = lutSubProducts;
	}

	@Id

	@Column(name = "PRODUCTID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getProductid() {
		return this.productid;
	}

	public void setProductid(Long productid) {
		this.productid = productid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MEASID")
	@JsonBackReference
	public LutMeasurements getLutMeasurements() {
		return this.lutMeasurements;
	}

	public void setLutMeasurements(LutMeasurements lutMeasurements) {
		this.lutMeasurements = lutMeasurements;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lutProducts")
	@JsonBackReference
	public Set<LnkWeeklyProduct> getLnkWeeklyProducts() {
		return this.lnkWeeklyProducts;
	}

	public void setLnkWeeklyProducts(Set<LnkWeeklyProduct> lnkWeeklyProducts) {
		this.lnkWeeklyProducts = lnkWeeklyProducts;
	}
	
	@Column(name = "PARENTDEPOSITID")
	public Long getDepositid() {
		return depositid;
	}

	public void setDepositid(Long depositid) {
		this.depositid = depositid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PARENTDEPOSITID",nullable = false,insertable=false,updatable=false)	
	@JsonBackReference
	public LutDeposit getLutDeposit() {
		return this.lutDeposit;
	}

	public void setLutDeposit(LutDeposit lutDeposit) {
		this.lutDeposit = lutDeposit;
	}

	@Column(name = "PRODUCTNAMEMON", nullable = false, length = 100)
	public String getProductnamemon() {
		return this.productnamemon;
	}

	public void setProductnamemon(String productnamemon) {
		this.productnamemon = productnamemon;
	}

	@Column(name = "PRODUCTNAMEENG", nullable = false, length = 100)
	public String getProductnameeng() {
		return this.productnameeng;
	}

	public void setProductnameeng(String productnameeng) {
		this.productnameeng = productnameeng;
	}




	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lutProducts")
	@JsonBackReference
	public Set<LutSubProduct> getLutSubProducts() {
		return this.lutSubProducts;
	}

	public void setLutSubProducts(Set<LutSubProduct> lutSubProducts) {
		this.lutSubProducts = lutSubProducts;
	}

}
