package com.peace.users.model.mram;
// Generated Nov 17, 2015 5:32:33 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LutReasons generated by hbm2java
 */
@Entity
@Table(name = "LUT_REASONS")
public class LutReasons implements java.io.Serializable {

	private Long reasonId;
	private String reasonNameMon;
	private String reasonNameEng;

	public LutReasons() {
	}

	public LutReasons(Long reasonId, String reasonNameMon, String reasonNameEng) {
		this.reasonId = reasonId;
		this.reasonNameMon = reasonNameMon;
		this.reasonNameEng = reasonNameEng;
	}

	@Id

	@Column(name = "ReasonID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getReasonId() {
		return this.reasonId;
	}

	public void setReasonId(Long reasonId) {
		this.reasonId = reasonId;
	}

	@Column(name = "ReasonNameMon", nullable = false, length = 100)
	public String getReasonNameMon() {
		return this.reasonNameMon;
	}

	public void setReasonNameMon(String reasonNameMon) {
		this.reasonNameMon = reasonNameMon;
	}

	@Column(name = "ReasonNameEng", nullable = false, length = 100)
	public String getReasonNameEng() {
		return this.reasonNameEng;
	}

	public void setReasonNameEng(String reasonNameEng) {
		this.reasonNameEng = reasonNameEng;
	}

}
