package com.peace.users.model.mram;
// Generated Nov 17, 2015 5:32:33 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * LutReporttype generated by hbm2java
 */
@Entity
@Table(name = "LUT_REPORTTYPE")
public class LutReporttype implements java.io.Serializable {

	private Long id;
	private String reportTypeNameMon;
	private String reportTypeNameEng;
	private Set<RegWeeklyMontly> regWeeklyMontlies = new HashSet<RegWeeklyMontly>(0);
	private Set<SubReportRegistration> subReportRegistrations = new HashSet<SubReportRegistration>(0);
	private Set<LnkFormreporttype> lnkFormreporttypes = new HashSet<LnkFormreporttype>(0);
	private Set<LutForms> lutFormses = new HashSet<LutForms>(0);

	public LutReporttype() {
	}

	public LutReporttype(Long id, String reportTypeNameMon, String reportTypeNameEng) {
		this.id = id;
		this.reportTypeNameMon = reportTypeNameMon;
		this.reportTypeNameEng = reportTypeNameEng;
	}

	public LutReporttype(Long id, String reportTypeNameMon, String reportTypeNameEng,
			Set<RegWeeklyMontly> regWeeklyMontlies, Set<SubReportRegistration> subReportRegistrations,
			Set<LnkFormreporttype> lnkFormreporttypes, Set<LutForms> lutFormses) {
		this.id = id;
		this.reportTypeNameMon = reportTypeNameMon;
		this.reportTypeNameEng = reportTypeNameEng;
		this.regWeeklyMontlies = regWeeklyMontlies;
		this.subReportRegistrations = subReportRegistrations;
		this.lnkFormreporttypes = lnkFormreporttypes;
		this.lutFormses = lutFormses;
	}

	@Id
	@SequenceGenerator(name="LUT_REPORTTYPE_SEQ", sequenceName="LUT_REPORTTYPE_SEQ", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="LUT_REPORTTYPE_SEQ")
	@Column(name = "ReportTypeID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	
	
	

	@Column(name = "ReportTypeNameMon", nullable = false, length = 50)
	public String getReportTypeNameMon() {
		return this.reportTypeNameMon;
	}



	public void setReportTypeNameMon(String reportTypeNameMon) {
		this.reportTypeNameMon = reportTypeNameMon;
	}

	@Column(name = "ReportTypeNameEng", nullable = false, length = 50)
	public String getReportTypeNameEng() {
		return this.reportTypeNameEng;
	}

	public void setReportTypeNameEng(String reportTypeNameEng) {
		this.reportTypeNameEng = reportTypeNameEng;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lutReporttype")
	public Set<RegWeeklyMontly> getRegWeeklyMontlies() {
		return this.regWeeklyMontlies;
	}

	public void setRegWeeklyMontlies(Set<RegWeeklyMontly> regWeeklyMontlies) {
		this.regWeeklyMontlies = regWeeklyMontlies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lutReporttype")
	public Set<SubReportRegistration> getSubReportRegistrations() {
		return this.subReportRegistrations;
	}

	public void setSubReportRegistrations(Set<SubReportRegistration> subReportRegistrations) {
		this.subReportRegistrations = subReportRegistrations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lutReporttype")
	public Set<LnkFormreporttype> getLnkFormreporttypes() {
		return this.lnkFormreporttypes;
	}

	public void setLnkFormreporttypes(Set<LnkFormreporttype> lnkFormreporttypes) {
		this.lnkFormreporttypes = lnkFormreporttypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lutReporttype")
	public Set<LutForms> getLutFormses() {
		return this.lutFormses;
	}

	public void setLutFormses(Set<LutForms> lutFormses) {
		this.lutFormses = lutFormses;
	}

}
