package com.peace.users.model.mram;
// Generated Dec 17, 2015 3:29:08 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PlanDataGeo1 generated by hbm2java
 */
@Entity
@Table(name = "PLAN_DATA_GEO_1")
public class PlanDataGeo1 implements java.io.Serializable {

	private BigDecimal id;
	private BigDecimal explorationId;
	private BigDecimal dataIndex;
	private String data1;
	private String data2;
	private BigDecimal data3;
	private BigDecimal data4;
	private BigDecimal data5;
	private BigDecimal data6;
	private BigDecimal data7;

	public PlanDataGeo1() {
	}

	public PlanDataGeo1(BigDecimal id) {
		this.id = id;
	}

	public PlanDataGeo1(BigDecimal id, BigDecimal explorationId, BigDecimal dataIndex, String data1, String data2,
			BigDecimal data3, BigDecimal data4, BigDecimal data5, BigDecimal data6, BigDecimal data7) {
		this.id = id;
		this.explorationId = explorationId;
		this.dataIndex = dataIndex;
		this.data1 = data1;
		this.data2 = data2;
		this.data3 = data3;
		this.data4 = data4;
		this.data5 = data5;
		this.data6 = data6;
		this.data7 = data7;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "EXPLORATION_ID", precision = 22, scale = 0)
	public BigDecimal getExplorationId() {
		return this.explorationId;
	}

	public void setExplorationId(BigDecimal explorationId) {
		this.explorationId = explorationId;
	}

	@Column(name = "DATA_INDEX", precision = 22, scale = 0)
	public BigDecimal getDataIndex() {
		return this.dataIndex;
	}

	public void setDataIndex(BigDecimal dataIndex) {
		this.dataIndex = dataIndex;
	}

	@Column(name = "DATA1")
	public String getData1() {
		return this.data1;
	}

	public void setData1(String data1) {
		this.data1 = data1;
	}

	@Column(name = "DATA2", length = 25)
	public String getData2() {
		return this.data2;
	}

	public void setData2(String data2) {
		this.data2 = data2;
	}

	@Column(name = "DATA3", precision = 22, scale = 0)
	public BigDecimal getData3() {
		return this.data3;
	}

	public void setData3(BigDecimal data3) {
		this.data3 = data3;
	}

	@Column(name = "DATA4", precision = 22, scale = 0)
	public BigDecimal getData4() {
		return this.data4;
	}

	public void setData4(BigDecimal data4) {
		this.data4 = data4;
	}

	@Column(name = "DATA5", precision = 22, scale = 0)
	public BigDecimal getData5() {
		return this.data5;
	}

	public void setData5(BigDecimal data5) {
		this.data5 = data5;
	}

	@Column(name = "DATA6", precision = 22, scale = 0)
	public BigDecimal getData6() {
		return this.data6;
	}

	public void setData6(BigDecimal data6) {
		this.data6 = data6;
	}

	@Column(name = "DATA7", precision = 22, scale = 0)
	public BigDecimal getData7() {
		return this.data7;
	}

	public void setData7(BigDecimal data7) {
		this.data7 = data7;
	}

}
