package com.peace.users.model.mram;
// Generated Nov 17, 2015 5:32:33 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * RegWeeklyMontly generated by hbm2java
 */
@Entity
@Table(name = "WEEKLY_MONTLY_DATA")
public class RegWeeklyMontly implements java.io.Serializable {

	private Long id;
	private LutReporttype lutReporttype;
	private LutForms lutForms;
//	private LutMeasurements lutMeasurements;
	private WeeklyRegistration weeklyRegistration;
	private LutAppstatus lutAppstatus;
	private SubLegalpersons subLegalpersons;
	private RegReportReq regReportReq;
	
	private Long ReportTypeID;
	private Long FormID;
	private Long MeasID;
	private Long RepStatusID;
	private String LpReg;
	private Integer LicenseNum;
	private Long wrid;
	private Integer lwid;
	private String startdate;
	private String enddate;
	private Integer year;
	private Integer month;
	
	
	private Long personId;
	private Long formIndex;
	private String submissionDate;
	private Long data1;
	private Long data2;
	private Long data3;
	private Long data4;
	private Long data5;
	private Long data6;
	private Long data7;
	private String note;

	public RegWeeklyMontly() {
	}

	public RegWeeklyMontly(Long id, LutReporttype lutReporttype, LutForms lutForms,
			LutAppstatus lutAppstatus, SubLegalpersons subLegalpersons,
			RegReportReq regReportReq, Long personId, Long formIndex, String submissionDate) {
		this.id = id;
		this.lutReporttype = lutReporttype;
		this.lutForms = lutForms;
	//	this.lutMeasurements = lutMeasurements;
		this.lutAppstatus = lutAppstatus;
		this.subLegalpersons = subLegalpersons;
		this.regReportReq = regReportReq;
		this.personId = personId;
		this.formIndex = formIndex;
		this.submissionDate = submissionDate;
	}

	public RegWeeklyMontly(Long id, LutReporttype lutReporttype, LutForms lutForms,
			LutAppstatus lutAppstatus, SubLegalpersons subLegalpersons,
			RegReportReq regReportReq, Long personId, Long formIndex, String submissionDate,
			Long data1, Long data2, Long data3, Long data4, Long data5,  String note) {
		this.id = id;
		this.lutReporttype = lutReporttype;
		this.lutForms = lutForms;
		this.lutAppstatus = lutAppstatus;
		this.subLegalpersons = subLegalpersons;
		this.regReportReq = regReportReq;
		this.personId = personId;
		this.formIndex = formIndex;
		this.submissionDate = submissionDate;
		this.data1 = data1;
		this.data2 = data2;
		this.data3 = data3;
		this.data4 = data4;
		this.data5 = data5;
		this.note = note;
	}
	@Id
	@SequenceGenerator(name="REG_WEEKLY_MONTLY_SEQ", sequenceName="REG_WEEKLY_MONTLY_SEQ", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="REG_WEEKLY_MONTLY_SEQ")
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ReportTypeID", nullable = false,insertable=false,updatable=false)
	 @JsonBackReference
	public LutReporttype getLutReporttype() {
		return this.lutReporttype;
	}

	public void setLutReporttype(LutReporttype lutReporttype) {
		this.lutReporttype = lutReporttype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FormID", nullable = false,insertable=false,updatable=false)
	@JsonBackReference
	public LutForms getLutForms() {
		return this.lutForms;
	}

	public void setLutForms(LutForms lutForms) {
		this.lutForms = lutForms;
	}

/*	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MeasID", nullable = false,insertable=false,updatable=false)
	@JsonBackReference
	public LutMeasurements getLutMeasurements() {
		return this.lutMeasurements;
	}

	public void setLutMeasurements(LutMeasurements lutMeasurements) {
		this.lutMeasurements = lutMeasurements;
	}
*/
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RepStatusID", nullable = false,insertable=false,updatable=false)
	@JsonBackReference
	public LutAppstatus getLutAppstatus() {
		return this.lutAppstatus;
	}

	public void setLutAppstatus(LutAppstatus lutAppstatus) {
		this.lutAppstatus = lutAppstatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LP_Reg", nullable = false,insertable=false,updatable=false)
	 @JsonBackReference
	public SubLegalpersons getSubLegalpersons() {
		return this.subLegalpersons;
	}

	public void setSubLegalpersons(SubLegalpersons subLegalpersons) {
		this.subLegalpersons = subLegalpersons;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LicenseNum", nullable = false,insertable=false,updatable=false)
	@JsonBackReference
	public RegReportReq getRegReportReq() {
		return this.regReportReq;
	}

	public void setRegReportReq(RegReportReq regReportReq) {
		this.regReportReq = regReportReq;
	}


	@Column(name = "ReportTypeID")
	public Long getReportTypeID() {
		return ReportTypeID;
	}

	public void setReportTypeID(Long reportTypeID) {
		ReportTypeID = reportTypeID;
	}

	@Column(name = "FormID")
	public Long getFormID() {
		return FormID;
	}

	public void setFormID(Long formID) {
		FormID = formID;
	}

	@Column(name = "MeasID")
	public Long getMeasID() {
		return MeasID;
	}

	public void setMeasID(Long measID) {
		MeasID = measID;
	}

	@Column(name = "RepStatusID")
	public Long getRepStatusID() {
		return RepStatusID;
	}

	public void setRepStatusID(Long repStatusID) {
		RepStatusID = repStatusID;
	}

	@Column(name = "LP_Reg")
	public String getLpReg() {
		return LpReg;
	}

	public void setLpReg(String lpReg) {
		LpReg = lpReg;
	}

	@Column(name = "LicenseNum")
	public Integer getLicenseNum() {
		return LicenseNum;
	}

	public void setLicenseNum(Integer licenseNum) {
		LicenseNum = licenseNum;
	}

	@Column(name = "PersonID")
	public Long getPersonId() {
		return this.personId;
	}

	public void setPersonId(Long personId) {
		this.personId = personId;
	}

	@Column(name = "FormIndex")
	public Long getFormIndex() {
		return this.formIndex;
	}

	public void setFormIndex(Long formIndex) {
		this.formIndex = formIndex;
	}

	@Column(name = "Submissiondate")
	public String getSubmissionDate() {
		return this.submissionDate;
	}

	public void setSubmissionDate(String submissionDate) {
		this.submissionDate = submissionDate;
	}

	@Column(name = "Data1", precision = 22, scale = 0)
	public Long getData1() {
		return this.data1;
	}

	public void setData1(Long data1) {
		this.data1 = data1;
	}

	@Column(name = "Data2", precision = 22, scale = 0)
	public Long getData2() {
		return this.data2;
	}

	public void setData2(Long data2) {
		this.data2 = data2;
	}

	@Column(name = "Data3", precision = 22, scale = 0)
	public Long getData3() {
		return this.data3;
	}

	public void setData3(Long data3) {
		this.data3 = data3;
	}

	@Column(name = "Data4", precision = 22, scale = 0)
	public Long getData4() {
		return this.data4;
	}

	public void setData4(Long data4) {
		this.data4 = data4;
	}

	@Column(name = "Data5", precision = 22, scale = 0)
	public Long getData5() {
		return this.data5;
	}

	public void setData5(Long data5) {
		this.data5 = data5;
	}

	
	@Column(name = "Data6", precision = 22, scale = 0)
	public Long getData6() {
		return data6;
	}

	public void setData6(Long data6) {
		this.data6 = data6;
	}

	@Column(name = "Data7", precision = 22, scale = 0)
	public Long getData7() {
		return data7;
	}

	public void setData7(Long data7) {
		this.data7 = data7;
	}

	@Column(name = "Note", length = 500)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}
	
	
	
	@Column(name = "WRID")
	public Long getWrid() {
		return wrid;
	}

	public void setWrid(Long wrid) {
		this.wrid = wrid;
	}

	@Column(name = "STARTDATE")
	public String getStartdate() {
		return startdate;
	}

	public void setStartdate(String startdate) {
		this.startdate = startdate;
	}

	@Column(name = "ENDDATE")
	public String getEnddate() {
		return enddate;
	}

	public void setEnddate(String enddate) {
		this.enddate = enddate;
	}

	@Column(name = "YEAR")
	public Integer getYear() {
		return year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	@Column(name = "MONTH")
	public Integer getMonth() {
		return month;
	}

	public void setMonth(Integer month) {
		this.month = month;
	}
		
	@Column(name = "LWID")
	public Integer getLwid() {
		return lwid;
	}

	public void setLwid(Integer lwid) {
		this.lwid = lwid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "WRID", nullable = false,insertable=false,updatable=false)
	@JsonBackReference
	public WeeklyRegistration getWeeklyRegistration() {
		return this.weeklyRegistration;
	}

	public void setWeeklyRegistration(WeeklyRegistration weeklyRegistration) {
		this.weeklyRegistration = weeklyRegistration;
	}
}
