package com.peace.users.model.mram;
// Generated Nov 18, 2015 5:50:18 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * SubApprovals generated by hbm2java
 */
@Entity
@Table(name = "SUB_APPROVALS")
public class SubApprovals implements java.io.Serializable {

	private Long approvalsid;
	private LutForms lutForms;
	private LutDecisions lutDecisions;
	private LutUsers lutUsers;
	private LutAppsteps lutAppsteps;
	private String approvaldate;
	private String note;

	public SubApprovals() {
	}

	public SubApprovals(Long approvalsid, LutForms lutForms, LutDecisions lutDecisions, LutUsers lutUsers,
			LutAppsteps lutAppsteps, String approvaldate, String note) {
		this.approvalsid = approvalsid;
		this.lutForms = lutForms;
		this.lutDecisions = lutDecisions;
		this.lutUsers = lutUsers;
		this.lutAppsteps = lutAppsteps;
		this.approvaldate = approvaldate;
		this.note = note;
	}

	@Id

	@Column(name = "APPROVALSID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getApprovalsid() {
		return this.approvalsid;
	}

	public void setApprovalsid(Long approvalsid) {
		this.approvalsid = approvalsid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FORMID", nullable = false)
	@JsonBackReference
	public LutForms getLutForms() {
		return this.lutForms;
	}

	public void setLutForms(LutForms lutForms) {
		this.lutForms = lutForms;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DECISIONID", nullable = false)
	@JsonBackReference
	public LutDecisions getLutDecisions() {
		return this.lutDecisions;
	}

	public void setLutDecisions(LutDecisions lutDecisions) {
		this.lutDecisions = lutDecisions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OFFICERID", nullable = false)
	@JsonBackReference
	public LutUsers getLutUsers() {
		return this.lutUsers;
	}

	public void setLutUsers(LutUsers lutUsers) {
		this.lutUsers = lutUsers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STEPSID", nullable = false)
	@JsonBackReference
	public LutAppsteps getLutAppsteps() {
		return this.lutAppsteps;
	}

	public void setLutAppsteps(LutAppsteps lutAppsteps) {
		this.lutAppsteps = lutAppsteps;
	}

	@Column(name = "APPROVALDATE", nullable = false, length = 10)
	@JsonBackReference
	public String getApprovaldate() {
		return this.approvaldate;
	}

	public void setApprovaldate(String approvaldate) {
		this.approvaldate = approvaldate;
	}

	@Column(name = "NOTE", nullable = false, length = 1000)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
