package com.peace.users.model.mram;
// Generated Nov 17, 2015 5:32:33 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * SubAddLpInfo generated by hbm2java
 */
@Entity
@Table(name = "SUB_ADD_LP_INFO")
public class SubAddLpInfo implements java.io.Serializable {

	private String lpReg;
	private SubLegalpersons subLegalpersons;
	private Long holderId;
	private String licenseId;
	private Integer mineralsId;
	private Integer personId;
	private String reportingPersonName;
	private String reportingPersonPhone;
	private String email;

	public SubAddLpInfo() {
	}

	public SubAddLpInfo(SubLegalpersons subLegalpersons, Long holderId, String licenseId, Integer mineralsId,
			Integer personId, String reportingPersonName, String reportingPersonPhone, String email) {
		this.subLegalpersons = subLegalpersons;
		this.holderId = holderId;
		this.licenseId = licenseId;
		this.mineralsId = mineralsId;
		this.personId = personId;
		this.reportingPersonName = reportingPersonName;
		this.reportingPersonPhone = reportingPersonPhone;
		this.email = email;
	}

	@Id
	@SequenceGenerator(name="SUB_ADD_LP_INFO_SEQ", sequenceName="SUB_ADD_LP_INFO_SEQ")
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="SUB_ADD_LP_INFO_SEQ")
	@Column(name = "HolderID", nullable = false, precision = 22, scale = 0)
	public Long getHolderId() {
		return this.holderId;
	}

	public void setHolderId(Long holderId) {
		this.holderId = holderId;
	}
	

	@Column(name = "LP_REG",  length = 7)
	public String getLpReg() {
		return this.lpReg;
	}

	public void setLpReg(String lpReg) {
		this.lpReg = lpReg;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LP_REG", referencedColumnName="LP_REG", nullable = false,insertable=false,updatable=false)
	@JsonBackReference
	public SubLegalpersons getSubLegalpersons() {
		return this.subLegalpersons;
	}

	public void setSubLegalpersons(SubLegalpersons subLegalpersons) {
		this.subLegalpersons = subLegalpersons;
	}

	

	@Column(name = "LicenseID",  length = 10)
	public String getLicenseId() {
		return this.licenseId;
	}

	public void setLicenseId(String licenseId) {
		this.licenseId = licenseId;
	}

	@Column(name = "MineralsID",  precision = 22, scale = 0)
	public Integer getMineralsId() {
		return this.mineralsId;
	}

	public void setMineralsId(Integer mineralsId) {
		this.mineralsId = mineralsId;
	}

	@Column(name = "PersonID",  precision = 22, scale = 0)
	public Integer getPersonId() {
		return this.personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}

	@Column(name = "ReportingPersonName",  length = 100)
	public String getReportingPersonName() {
		return this.reportingPersonName;
	}

	public void setReportingPersonName(String reportingPersonName) {
		this.reportingPersonName = reportingPersonName;
	}

	@Column(name = "ReportingPersonPhone",  length = 20)
	public String getReportingPersonPhone() {
		return this.reportingPersonPhone;
	}

	public void setReportingPersonPhone(String reportingPersonPhone) {
		this.reportingPersonPhone = reportingPersonPhone;
	}

	@Column(name = "Email",  length = 70)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
