package com.peace.users.model.mram;
// Generated Mar 22, 2016 11:48:00 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * SubContract generated by hbm2java
 */
@Entity
@Table(name = "SUB_CONTRACT")
public class SubContract implements java.io.Serializable {

	private Long id;
	private LnkReqAnn lnkReqAnn;
	private String licensenum;
	private String lpReg;
	private String contractstatus;
	private String contractdate;
	private Long contractamount;
	private Long paid;
	private Long balance;
	private Long currentpayment;
	private Long reqannid;
	private String conclusiondate;

	public SubContract() {
	}

	public SubContract(Long id) {
		this.id = id;
	}

	public SubContract(Long id, LnkReqAnn lnkReqAnn, String licensenum, String lpReg, String contractstatus,
			String contractdate, Long contractamount, Long paid, Long balance,
			Long currentpayment, String conclusiondate) {
		this.id = id;
		this.lnkReqAnn = lnkReqAnn;
		this.licensenum = licensenum;
		this.lpReg = lpReg;
		this.contractstatus = contractstatus;
		this.contractdate = contractdate;
		this.contractamount = contractamount;
		this.paid = paid;
		this.balance = balance;
		this.currentpayment = currentpayment;
		this.conclusiondate = conclusiondate;
	}

	@Id	
	@SequenceGenerator(name="SUB_CONTRACT_SEQ", sequenceName="SUB_CONTRACT_SEQ", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="SUB_CONTRACT_SEQ")
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	
	
	
	@Column(name = "REQANNID", length = 20)
	public Long getReqannid() {
		return reqannid;
	}

	public void setReqannid(Long reqannid) {
		this.reqannid = reqannid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REQANNID",insertable=false,updatable=false,nullable=false)
	@JsonBackReference
	public LnkReqAnn getLnkReqAnn() {
		return this.lnkReqAnn;
	}

	public void setLnkReqAnn(LnkReqAnn lnkReqAnn) {
		this.lnkReqAnn = lnkReqAnn;
	}

	@Column(name = "LICENSENUM", length = 20)
	public String getLicensenum() {
		return this.licensenum;
	}

	public void setLicensenum(String licensenum) {
		this.licensenum = licensenum;
	}

	@Column(name = "LP_REG", length = 7)
	public String getLpReg() {
		return this.lpReg;
	}

	public void setLpReg(String lpReg) {
		this.lpReg = lpReg;
	}

	@Column(name = "CONTRACTSTATUS", length = 50)
	public String getContractstatus() {
		return this.contractstatus;
	}

	public void setContractstatus(String contractstatus) {
		this.contractstatus = contractstatus;
	}

	@Column(name = "CONTRACTDATE", length = 30)
	public String getContractdate() {
		return this.contractdate;
	}

	public void setContractdate(String contractdate) {
		this.contractdate = contractdate;
	}

	@Column(name = "CONTRACTAMOUNT", precision = 22, scale = 0)
	public Long getContractamount() {
		return this.contractamount;
	}

	public void setContractamount(Long contractamount) {
		this.contractamount = contractamount;
	}

	@Column(name = "PAID", precision = 22, scale = 0)
	public Long getPaid() {
		return this.paid;
	}

	public void setPaid(Long paid) {
		this.paid = paid;
	}

	@Column(name = "BALANCE", precision = 22, scale = 0)
	public Long getBalance() {
		return this.balance;
	}

	public void setBalance(Long balance) {
		this.balance = balance;
	}

	@Column(name = "CURRENTPAYMENT", precision = 22, scale = 0)
	public Long getCurrentpayment() {
		return this.currentpayment;
	}

	public void setCurrentpayment(Long currentpayment) {
		this.currentpayment = currentpayment;
	}

	@Column(name = "CONCLUSIONDATE", length = 30)
	public String getConclusiondate() {
		return this.conclusiondate;
	}

	public void setConclusiondate(String conclusiondate) {
		this.conclusiondate = conclusiondate;
	}

}
