package com.peace.users.model.mram;
// Generated Mar 22, 2016 11:48:00 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * SubNoContract generated by hbm2java
 */
@Entity
@Table(name = "SUB_NO_CONTRACT")
public class SubNoContract implements java.io.Serializable {

	private Long id;
	private LnkReqAnn lnkReqAnn;
	private String licensenum;
	private String lpReg;
	private String requeststatus;
	private String requestdate;
	private String mramregid;
	private String reference;
	private String mramdate;
	private String mramletterid;
	private Long reqannid;
	public SubNoContract() {
	}

	public SubNoContract(Long id) {
		this.id = id;
	}

	public SubNoContract(Long id, LnkReqAnn lnkReqAnn, String licensenum, String lpReg, String requeststatus,
			String requestdate, String mramregid, String reference, String mramdate, String mramletterid) {
		this.id = id;
		this.lnkReqAnn = lnkReqAnn;
		this.licensenum = licensenum;
		this.lpReg = lpReg;
		this.requeststatus = requeststatus;
		this.requestdate = requestdate;
		this.mramregid = mramregid;
		this.reference = reference;
		this.mramdate = mramdate;
		this.mramletterid = mramletterid;
	}

	@Id
	@SequenceGenerator(name="SUB_CONTRACT_NO_SEQ", sequenceName="SUB_CONTRACT_NO_SEQ", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="SUB_CONTRACT_NO_SEQ")
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	
	@Column(name = "REQANNID", length = 20)
	public Long getReqannid() {
		return reqannid;
	}

	public void setReqannid(Long reqannid) {
		this.reqannid = reqannid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REQANNID",insertable=false,updatable=false,nullable=false)
	@JsonBackReference
	public LnkReqAnn getLnkReqAnn() {
		return this.lnkReqAnn;
	}

	public void setLnkReqAnn(LnkReqAnn lnkReqAnn) {
		this.lnkReqAnn = lnkReqAnn;
	}

	@Column(name = "LICENSENUM", length = 20)
	public String getLicensenum() {
		return this.licensenum;
	}

	public void setLicensenum(String licensenum) {
		this.licensenum = licensenum;
	}

	@Column(name = "LP_REG", length = 7)
	public String getLpReg() {
		return this.lpReg;
	}

	public void setLpReg(String lpReg) {
		this.lpReg = lpReg;
	}

	@Column(name = "REQUESTSTATUS", length = 50)
	public String getRequeststatus() {
		return this.requeststatus;
	}

	public void setRequeststatus(String requeststatus) {
		this.requeststatus = requeststatus;
	}

	@Column(name = "REQUESTDATE", length = 30)
	public String getRequestdate() {
		return this.requestdate;
	}

	public void setRequestdate(String requestdate) {
		this.requestdate = requestdate;
	}

	@Column(name = "MRAMREGID", length = 30)
	public String getMramregid() {
		return this.mramregid;
	}

	public void setMramregid(String mramregid) {
		this.mramregid = mramregid;
	}

	@Column(name = "REFERENCE")
	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	@Column(name = "MRAMDATE", length = 30)
	public String getMramdate() {
		return this.mramdate;
	}

	public void setMramdate(String mramdate) {
		this.mramdate = mramdate;
	}

	@Column(name = "MRAMLETTERID", length = 30)
	public String getMramletterid() {
		return this.mramletterid;
	}

	public void setMramletterid(String mramletterid) {
		this.mramletterid = mramletterid;
	}

}
