package com.peace.users.model.mram;
// Generated Feb 1, 2016 8:06:02 PM by Hibernate Tools 4.3.1.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * WeeklyRegistration generated by hbm2java
 */
@Entity
@Table(name = "WEEKLY_REGISTRATION")
public class WeeklyRegistration implements java.io.Serializable {

	private Long id;
	private RegReportReq regReportReq;
	private String licenseXB;
	private Integer licensenum;
	private String lpReg;
	private String lpName;
	private Integer reporttype;
	private Integer lictype;
	private Long repstatusid;
	private Long reqid;
	private String submissiondate;
	private Long personid;
	private Long officerid;
	private String approveddate;
	private String commenttext;
	private Long repstepid;
	private Long divisionid;
	private String weekstr;
	private Integer weekid;
	private Integer year;
	private Set<RegWeeklyMontly> regWeeklyMontlies = new HashSet<RegWeeklyMontly>(0);
	private List<LnkCommentWeekly> lnkCommentWeeklies = new ArrayList<LnkCommentWeekly>();
	private SubLegalpersons subLegalpersons;
	public WeeklyRegistration() {
	}

	public WeeklyRegistration(Long id) {
		this.id = id;
	}

	public WeeklyRegistration(Long id, RegReportReq regReportReq, Integer licensenum, String lpReg,
			Integer reporttype, Integer lictype, Long repstatusid, String submissiondate, Long personid,
			Long officerid, String approveddate, Long repstepid, Long divisionid, Integer weekid,
			Set<RegWeeklyMontly> regWeeklyMontlies) {
		this.id = id;
		this.regReportReq = regReportReq;
		this.licensenum = licensenum;
		this.lpReg = lpReg;
		this.reporttype = reporttype;
		this.lictype = lictype;
		this.repstatusid = repstatusid;
		this.submissiondate = submissiondate;
		this.personid = personid;
		this.officerid = officerid;
		this.approveddate = approveddate;
		this.repstepid = repstepid;
		this.divisionid = divisionid;
		this.weekid = weekid;
		this.regWeeklyMontlies = regWeeklyMontlies;
	}

	@Id
	@SequenceGenerator(name="WEEKLY_REGISTRATION_SEQ", sequenceName="WEEKLY_REGISTRATION_SEQ", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="WEEKLY_REGISTRATION_SEQ")	
	@Column(name = "ID", unique = true,  nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	
	@Column(name = "REQID")
	public Long getReqid() {
		return reqid;
	}

	public void setReqid(Long reqid) {
		this.reqid = reqid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REQID",nullable=false,insertable=false,updatable=false)
	@JsonBackReference
	public RegReportReq getRegReportReq() {
		return this.regReportReq;
	}

	public void setRegReportReq(RegReportReq regReportReq) {
		this.regReportReq = regReportReq;
	}

	@Column(name = "LICENSENUM", length = 20)
	public Integer getLicensenum() {
		return this.licensenum;
	}

	public void setLicensenum(Integer licensenum) {
		this.licensenum = licensenum;
	}

	@Column(name = "LP_REG", length = 7)
	public String getLpReg() {
		return this.lpReg;
	}

	public void setLpReg(String lpReg) {
		this.lpReg = lpReg;
	}
	
	
	@Column(name = "LICENSEXB")
	public String getLicenseXB() {
		return licenseXB;
	}

	public void setLicenseXB(String licenseXB) {
		this.licenseXB = licenseXB;
	}

	@Column(name = "LP_NAME")
	public String getLpName() {
		return lpName;
	}

	public void setLpName(String lpName) {
		this.lpName = lpName;
	}

	@Column(name = "REPORTTYPE", precision = 7, scale = 0)
	public Integer getReporttype() {
		return this.reporttype;
	}

	public void setReporttype(Integer reporttype) {
		this.reporttype = reporttype;
	}

	@Column(name = "LICTYPE", precision = 7, scale = 0)
	public Integer getLictype() {
		return this.lictype;
	}

	public void setLictype(Integer lictype) {
		this.lictype = lictype;
	}

	@Column(name = "REPSTATUSID", precision = 22, scale = 0)
	public Long getRepstatusid() {
		return this.repstatusid;
	}

	public void setRepstatusid(Long repstatusid) {
		this.repstatusid = repstatusid;
	}

	@Column(name = "SUBMISSIONDATE", length = 30)
	public String getSubmissiondate() {
		return this.submissiondate;
	}

	public void setSubmissiondate(String submissiondate) {
		this.submissiondate = submissiondate;
	}

	@Column(name = "PERSONID", precision = 22, scale = 0)
	public Long getPersonid() {
		return this.personid;
	}

	public void setPersonid(Long personid) {
		this.personid = personid;
	}

	@Column(name = "OFFICERID", precision = 22, scale = 0)
	public Long getOfficerid() {
		return this.officerid;
	}

	public void setOfficerid(Long officerid) {
		this.officerid = officerid;
	}

	@Column(name = "APPROVEDDATE", length = 200)
	public String getApproveddate() {
		return this.approveddate;
	}

	public void setApproveddate(String approveddate) {
		this.approveddate = approveddate;
	}

	@Column(name = "REPSTEPID", precision = 22, scale = 0)
	public Long getRepstepid() {
		return this.repstepid;
	}

	public void setRepstepid(Long repstepid) {
		this.repstepid = repstepid;
	}

	@Column(name = "DIVISIONID", precision = 22, scale = 0)
	public Long getDivisionid() {
		return this.divisionid;
	}

	public void setDivisionid(Long divisionid) {
		this.divisionid = divisionid;
	}

	@Column(name = "WEEKID", precision = 22, scale = 0)
	public Integer getWeekid() {
		return this.weekid;
	}

	public void setWeekid(Integer weekid) {
		this.weekid = weekid;
	}
	
	
	@Column(name = "WEEKSTR")
	public String getWeekstr() {
		return weekstr;
	}

	public void setWeekstr(String weekstr) {
		this.weekstr = weekstr;
	}

	@Column(name = "YEAR")
	public Integer getYear() {
		return year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}
		
	@Column(name = "COMMENTTEXT")
	public String getCommenttext() {
		return commenttext;
	}

	public void setCommenttext(String commenttext) {
		this.commenttext = commenttext;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "weeklyRegistration")
	@JsonBackReference
	public Set<RegWeeklyMontly> getRegWeeklyMontlies() {
		return this.regWeeklyMontlies;
	}

	public void setRegWeeklyMontlies(Set<RegWeeklyMontly> regWeeklyMontlies) {
		this.regWeeklyMontlies = regWeeklyMontlies;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LP_REG", referencedColumnName="LP_REG", nullable=false,insertable=false,updatable=false)
	@JsonBackReference
	public SubLegalpersons getSubLegalpersons() {
		return this.subLegalpersons;
	}

	public void setSubLegalpersons(SubLegalpersons subLegalpersons) {
		this.subLegalpersons = subLegalpersons;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "weeklyRegistration")
	@JsonBackReference
	public List<LnkCommentWeekly> getLnkCommentWeeklies() {
		return this.lnkCommentWeeklies;
	}

	public void setLnkCommentWeeklies(List<LnkCommentWeekly> lnkCommentWeeklies) {
		this.lnkCommentWeeklies = lnkCommentWeeklies;
	}
}
